const septemberPosters=[
['Chidambaram Nataraja Temple','heritage'],['Sripuram Golden Temple, Vellore','heritage'],['Tranquebar Danish Fort','heritage'],['Gangaikonda Cholapuram Temple','heritage'],['Airavatesvara Temple, Darasuram','heritage'],['Marudhamalai Temple, Coimbatore','heritage'],['Aliyar Dam, Pollachi','water'],['Top Slip, Anamalai Tiger Reserve','hills'],['Mudumalai National Park','hills'],['Kotagiri Hill Town','hills'],['Sathyamangalam Forest','hills'],['Javadi Hills','hills'],['Pachamalai Hills','hills'],['Meghamalai','hills'],['Sirumalai Hills, Dindigul','hills'],['Pillar Rocks, Kodaikanal','hills'],["Coaker's Walk, Kodaikanal",'hills'],['Muthupet Mangrove Forest','water'],['Semmozhi Poonga, Chennai','hills'],['Guindy National Park, Chennai','hills'],['Poompuhar Coast','water'],['Nagapattinam Coast','water'],['Karaikal Beach','water'],['Silver Beach, Cuddalore','water'],['Promenade, Pondicherry','water'],['Suchindram Temple, Nagercoil','heritage'],['Bhavani Sangam, Erode','water'],['Amaravathi Dam, Udumalpet','water'],['Pulicat Lake','water'],['Kalvarayan Hills','hills']
].map((x,i)=>({title:x[0],category:x[1],src:`assets/${String(i+1).padStart(2,'0')}.png`}));
const septemberCaptions=[
`Your health changes when you take ownership of the next small decision. Begin with one meal, one walk and one promise you can keep today. Save this and choose yourself again tomorrow.\n\n#DoctorFarmer #HealthOwnership #DailyHabits #SelfDiscipline #TamilNadu`,
`The transformation people admire is usually built before sunrise, when nobody is watching. Create a morning routine your future self will thank you for. Share this with someone building quietly.\n\n#MorningRoutine #Consistency #HealthyLifestyle #GrowthMindset #DoctorFarmer`,
`Old patterns feel permanent only because they have been repeated for years. Interrupt one today and make room for a stronger version of you. Comment with the habit you are leaving behind.\n\n#BreakThePattern #BetterHabits #MindsetShift #PersonalGrowth #DoctorFarmer`,
`Great bodies and resilient minds are constructed through ordinary repetitions. Every thoughtful meal and every completed set adds another brick. Save this reminder and keep building.\n\n#FitnessJourney #OneRepAtATime #Discipline #HealthyBody #DoctorFarmer`,
`Action creates momentum long before inspiration arrives. Start imperfectly, stay consistent and let progress become your motivation. Send this to someone waiting for the perfect moment.\n\n#TakeAction #NoMoreWaiting #FitnessMotivation #DailyProgress #DoctorFarmer`,
`A focused hour can change more than a distracted week. Decide what matters, remove one delay and move with purpose today. Save this for the moment procrastination returns.\n\n#ActNow #Focus #Urgency #HealthyHabits #DoctorFarmer`,
`Energy is a limited resource. Protect it from needless arguments, endless scrolling and commitments that pull you away from your wellbeing. Choose where your strength goes.\n\n#ProtectYourEnergy #Wellbeing #MindfulLiving #HealthFirst #DoctorFarmer`,
`The strongest routines do not depend on the day of the week. Choose a standard and honour it even when enthusiasm is low. Tag your accountability partner.\n\n#MondayMindset #ConsistencyWins #Routine #SelfDiscipline #DoctorFarmer`,
`Real discipline is steady, adaptable and stronger than a passing feeling. Train yourself to follow the plan while emotions rise and fall. Save this for a difficult day.\n\n#Discipline #MentalStrength #FitnessMindset #DailyHabits #DoctorFarmer`,
`Ease can quietly charge you with lost time, declining energy and delayed dreams. Choose useful discomfort now for greater freedom later. What challenge will you accept today?\n\n#LeaveComfortZone #Growth #HealthyChoices #Motivation #DoctorFarmer`,
`Nature responds to preparation, not negotiation—and the body works the same way. Respect sleep, movement and nourishment as daily essentials. Share this health reminder.\n\n#HealthDiscipline #BodyCare #Wellness #HealthyRoutine #DoctorFarmer`,
`Exhaustion is sometimes a signal to rest, but inconsistency can also make every task feel heavier. Recover honestly, then return to your routine with intention. Save this balanced reminder.\n\n#RestAndReset #Consistency #SelfAwareness #WellnessJourney #DoctorFarmer`,
`A strong future grows from modest actions repeated with care. Never underestimate a short walk, a simple meal or an earlier bedtime. Plant one better habit today.\n\n#SmallHabits #BigResults #HealthyFuture #DailyWellness #DoctorFarmer`,
`Uncertainty does not mean you must stop. Keep taking the next visible step until clarity catches up with your effort. Send this to someone navigating a difficult season.\n\n#KeepGoing #Clarity #Resilience #GrowthMindset #DoctorFarmer`,
`Healthy change needs patience before proof appears. Keep watering the routine even when results are still beneath the surface. Save this and trust your process.\n\n#TrustTheProcess #HealthyHabits #Patience #FitnessJourney #DoctorFarmer`,
`Strength is not the absence of difficult weather; it is the ability to stay grounded through it. Build routines that hold you steady when life becomes unpredictable.\n\n#StayStrong #Resilience #MentalFitness #Discipline #DoctorFarmer`,
`Progress begins just beyond the point where comfort asks you to retreat. Take one safe, meaningful step toward the challenge you have been avoiding. Share this with a brave friend.\n\n#ChooseGrowth #Courage #PersonalDevelopment #HealthyMindset #DoctorFarmer`,
`Visible success depends on invisible foundations. Strengthen sleep, nutrition, movement and mental health before chasing shortcuts. Save this foundation checklist.\n\n#StrongFoundation #HolisticHealth #SleepNutritionMovement #DoctorFarmer`,
`A full calendar still needs space for your wellbeing. Protect a small appointment with yourself today and treat it as seriously as any meeting. When is your health hour?\n\n#MakeTimeForHealth #UrbanWellness #SelfCare #HealthySchedule #DoctorFarmer`,
`Your surroundings may be demanding, but your standards can still survive. Keep a simple routine that works even on noisy, crowded and difficult days. Save it for your busiest week.\n\n#UrbanHealth #WildDiscipline #Routine #HealthyLiving #DoctorFarmer`,
`History reminds us that even powerful things can disappear. Let the habits holding you back end here, and carry only what strengthens your future.\n\n#LetGo #NewBeginning #MindsetReset #PersonalGrowth #DoctorFarmer`,
`Professionals honour the work even when the feeling is absent. Treat your wellbeing with the same responsibility: prepare, show up and complete the task. Tag someone dependable.\n\n#ShowUpDaily #WorkEthic #HealthCommitment #Discipline #DoctorFarmer`,
`Most progress happens away from applause. Keep doing the early, repetitive and unglamorous work until the outcome introduces you. Save this for tomorrow morning.\n\n#UnseenWork #EarlyMorning #Consistency #Results #DoctorFarmer`,
`A clear direction makes a large challenge manageable. Choose one path, remove distractions and take the next step without comparing lanes.\n\n#StayInYourLane #Focus #DailyProgress #Mindset #DoctorFarmer`,
`Consistency has a rhythm that continues through changing emotions. Build a routine simple enough to repeat and strong enough to carry you forward. Share this with your routine partner.\n\n#RoutineMatters #Consistency #CoastalMindset #HealthyHabits #DoctorFarmer`,
`The body you respect is built through devotion to daily practices, not occasional intensity. Approach food, movement and recovery with patience and sincerity.\n\n#BodyRespect #DedicatedLiving #FitnessDiscipline #HealthJourney #DoctorFarmer`,
`Wellbeing improves when its essential parts flow together. Align restorative sleep, nourishing food and regular movement instead of fixing only one piece. Save this three-part plan.\n\n#SleepFoodMovement #BalancedHealth #WellnessPlan #DoctorFarmer`,
`Recovery is productive when it prepares you to return stronger. Schedule rest before exhaustion forces it, and protect your capacity for what matters.\n\n#StrategicRest #Recovery #EnergyManagement #HealthyLifestyle #DoctorFarmer`,
`Sometimes growth requires changing the environment around you. Seek people, places and routines that support the person you are becoming. What condition will you improve first?\n\n#HealthyEnvironment #ChooseBetter #GrowthConditions #DoctorFarmer`,
`A meaningful climb begins with a chosen destination and deliberate direction. Define your health goal, map the habits and keep driving forward one day at a time.\n\n#HealthGoals #IntentionalLiving #DailyDiscipline #DoctorFarmer`
];
const augustPosters=[
 ['Vandalur Zoo, Chennai','hills','assets/august-26.png'],
 ['Tiruparankundram Murugan Temple, Madurai','heritage','assets/august-27.png'],
 ['Kottai Mariamman Temple, Salem','heritage','assets/august-28.png'],
 ['Sathanur Dam, Tiruvannamalai district','water','assets/august-29.png'],
 ['Sittanavasal Cave, Pudukkottai','heritage','assets/august-30.png'],
 ['Yercaud Lake, Salem district','water','assets/august-31.png']
].map(x=>({title:x[0],category:x[1],src:x[2]}));
const augustCaptions=[
`A calmer morning is not an empty morning. Move with intention, protect your attention and let a steady beginning shape the rest of your day.\n\n#DoctorFarmer #CalmMorning #MindfulLiving #VandalurZoo #Chennai`,
`The strongest foundations are rarely rushed. Give your health the patience, repetition and care required to last for generations.\n\n#DoctorFarmer #Patience #HealthyHabits #Tiruparankundram #Madurai`,
`Real strength grows through honest effort repeated quietly. You do not need a perfect day—only one meaningful action you can complete today.\n\n#DoctorFarmer #DailyEffort #Consistency #KottaiMariamman #Salem`,
`Calm is not weakness; it is stored power. Pause before reacting, choose what deserves your energy and move with clarity.\n\n#DoctorFarmer #FindYourCalm #MentalWellbeing #SathanurDam #TamilNadu`,
`Time honours what is built with care. Choose one habit today that your future self will be grateful to inherit.\n\n#DoctorFarmer #BuildToday #HealthyFuture #Sittanavasal #Pudukkottai`,
`A peaceful morning is another chance to begin well. Receive it fully, breathe deeply and choose a pace you can sustain.\n\n#DoctorFarmer #MorningGift #Wellbeing #YercaudLake #Salem`
];
let posters=septemberPosters,captions=septemberCaptions;
const calendar=document.querySelector('#calendar'),startInput=document.querySelector('#start-date'),viewer=document.querySelector('#viewer'),viewerImage=document.querySelector('#viewer-image'),viewerTitle=document.querySelector('#viewer-title'),viewerCount=document.querySelector('#viewer-count'),viewerCaption=document.querySelector('#viewer-caption'),viewerDate=document.querySelector('#viewer-date'),viewerLocation=document.querySelector('#viewer-location'),copyCaptionButton=document.querySelector('.copy-caption');
let current=0,visible=[...posters.keys()],activeFilter='all';
const dayFmt=new Intl.DateTimeFormat('en-IN',{weekday:'short',day:'numeric',month:'short'}),rangeFmt=new Intl.DateTimeFormat('en-IN',{day:'numeric',month:'short',year:'numeric'});
const campaigns=Array.from({length:12},(_,i)=>{const d=new Date(2026,7+i,1),isAugust=i===0,isSeptember=i===1;return{key:`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`,label:d.toLocaleDateString('en-IN',{month:'long',year:'numeric'}),ready:isAugust||isSeptember,count:isAugust?6:isSeptember?30:0,target:isAugust?6:30,cover:isAugust?'assets/august-26.png':isSeptember?'assets/01.png':null,note:'Next monthly collection',startDate:isAugust?'2026-08-26':`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-01`,posts:isAugust?augustPosters:isSeptember?septemberPosters:null,captions:isAugust?augustCaptions:isSeptember?septemberCaptions:null}});
function renderMonthCards(){const host=document.querySelector('#month-cards');host.innerHTML='';campaigns.forEach(c=>{const button=document.createElement('button');button.className=`month-card${c.key===startInput.value.slice(0,7)?' active':''}${c.ready?'':' pending'}`;button.disabled=!c.ready;button.innerHTML=c.ready?`<img src="${c.cover}" alt=""><span class="month-card-shade"></span><span class="month-card-copy"><small>READY · ${c.count}/${c.target} POSTS</small><strong>${c.label}</strong><em>Open collection →</em></span>`:`<span class="month-card-empty">+</span><span class="month-card-copy"><small>AWAITING POSTERS · ${c.count}/${c.target}</small><strong>${c.label}</strong><em>${c.note}</em></span>`;button.addEventListener('click',()=>{startInput.value=c.startDate;posters=c.posts;captions=c.captions;activeFilter='all';document.querySelectorAll('.filter').forEach(filter=>filter.classList.toggle('active',filter.dataset.filter==='all'));document.querySelector('#selected-month').textContent=c.label;renderMonthCards();render();document.querySelector('.schedule-bar').scrollIntoView({behavior:'smooth'})});host.append(button)})}
function dateFor(i){const d=new Date(`${startInput.value}T12:00:00`);d.setDate(d.getDate()+i);return d}
function render(filter=activeFilter){
 activeFilter=filter;visible=[];calendar.innerHTML='';const grid=document.createElement('div');grid.className='grid';
 posters.forEach((p,i)=>{if(filter!=='all'&&p.category!==filter)return;visible.push(i);const d=dateFor(i),card=document.createElement('article');card.className='card';card.innerHTML=`<button class="poster-button" data-index="${i}" aria-label="View ${p.title} poster scheduled for ${dayFmt.format(d)}"><span class="date-badge"><strong>${d.getDate()}</strong><span>${d.toLocaleDateString('en-IN',{weekday:'short'}).toUpperCase()}</span></span><img src="${p.src}" alt="Motivational health poster photographed at ${p.title}" loading="lazy"></button><button class="card-copy" type="button" data-index="${i}" aria-label="Copy caption and download ${p.title} poster"><span aria-hidden="true">⇩</span> Download + copy</button><div class="meta"><span class="num">${String(i+1).padStart(2,'0')}</span><div><h3>${p.title}</h3><p>${dayFmt.format(d)} · ${p.category==='heritage'?'Heritage':p.category==='hills'?'Hills & forest':'Water & coast'}</p></div></div>`;grid.append(card)});
 calendar.append(grid);
 document.querySelectorAll('.filter').forEach(button=>{const count=button.dataset.filter==='all'?posters.length:posters.filter(p=>p.category===button.dataset.filter).length;button.querySelector('span').textContent=count});document.querySelector('#empty').hidden=visible.length>0;document.querySelector('#schedule-range').textContent=`${rangeFmt.format(dateFor(0))} — ${rangeFmt.format(dateFor(posters.length-1))}`;document.querySelector('#schedule-note').textContent=`One Instagram post every day for ${posters.length} days`;
}
function openViewer(i){current=i;const p=posters[i],d=dateFor(i);viewerImage.src=p.src;viewerImage.alt=`Motivational poster at ${p.title}`;viewerTitle.textContent=`Post ${String(i+1).padStart(2,'0')} of ${posters.length}`;viewerCount.textContent=`${posters.length}-day health series`;viewerCaption.textContent=captions[i];viewerLocation.textContent=p.title;viewerDate.textContent=dayFmt.format(d).toUpperCase();copyCaptionButton.classList.remove('copied');copyCaptionButton.lastChild.textContent=' Copy + download';viewer.showModal()}
function move(dir){const pos=visible.indexOf(current);current=visible[(pos+dir+visible.length)%visible.length];openViewer(current)}
function completeCaption(index=current){return `@iamdoctorfarmer For appointments:\n+91 89259 54625\n+91 72004 24271\n\n${captions[index]}`}
async function posterBlob(index=current){try{const response=await fetch(posters[index].src);if(response.ok)return await response.blob()}catch(error){}const image=new Image();image.src=posters[index].src;await image.decode();const canvas=document.createElement('canvas');canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;canvas.getContext('2d').drawImage(image,0,0);return await new Promise((resolve,reject)=>{try{canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('Image conversion failed')),'image/png')}catch(error){reject(error)}})}
async function downloadPoster(index=current){const blob=await posterBlob(index),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`doctor-farmer-post-${String(index+1).padStart(2,'0')}.png`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function setActionLabel(button,label){if(button===copyCaptionButton)button.lastChild.textContent=` ${label}`;else button.innerHTML=`<span aria-hidden="true">⇩</span> ${label}`}
async function copyCaption(index=current,button=copyCaptionButton){current=index;const text=completeCaption(index);setActionLabel(button,'Preparing…');button.disabled=true;let copied=false,downloaded=false;try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(text)}else{const area=document.createElement('textarea');area.value=text;area.setAttribute('readonly','');area.style.cssText='position:fixed;opacity:0;pointer-events:none';document.body.append(area);area.select();if(!document.execCommand('copy'))throw new Error('Copy failed');area.remove()}copied=true}catch(error){}try{await downloadPoster(index);downloaded=true}catch(error){}if(copied&&downloaded){button.classList.add('copied');setActionLabel(button,'Copied + downloaded!')}else if(copied){setActionLabel(button,'Copied · download blocked')}else if(downloaded){setActionLabel(button,'Downloaded · copy blocked')}else{setActionLabel(button,'Browser blocked both')}setTimeout(()=>{button.classList.remove('copied');button.disabled=false;setActionLabel(button,button===copyCaptionButton?'Copy + download':'Download + copy')},2600)}
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelector('.filter.active').classList.remove('active');b.classList.add('active');render(b.dataset.filter)}));
calendar.addEventListener('click',e=>{const copy=e.target.closest('.card-copy');if(copy){copyCaption(Number(copy.dataset.index),copy);return}const poster=e.target.closest('.poster-button');if(poster)openViewer(Number(poster.dataset.index))});document.querySelector('.close').onclick=()=>viewer.close();document.querySelector('.prev').onclick=()=>move(-1);document.querySelector('.next').onclick=()=>move(1);document.querySelector('.like').onclick=e=>{e.currentTarget.classList.toggle('liked');e.currentTarget.textContent=e.currentTarget.classList.contains('liked')?'♥':'♡'};copyCaptionButton.addEventListener('click',()=>copyCaption(current,copyCaptionButton));viewer.addEventListener('click',e=>{if(e.target===viewer)viewer.close()});document.addEventListener('keydown',e=>{if(!viewer.open)return;if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1)});startInput.value='2026-09-01';document.querySelector('#selected-month').textContent='September 2026';renderMonthCards();render();
