const septemberPosters=[
['Chidambaram Nataraja Temple','heritage'],['Sripuram Golden Temple, Vellore','heritage'],['Tranquebar Danish Fort','heritage'],['Gangaikonda Cholapuram Temple','heritage'],['Airavatesvara Temple, Darasuram','heritage'],['Marudhamalai Temple, Coimbatore','heritage'],['Aliyar Dam, Pollachi','water'],['Top Slip, Anamalai Tiger Reserve','hills'],['Mudumalai National Park','hills'],['Kotagiri Hill Town','hills'],['Sathyamangalam Forest','hills'],['Javadi Hills','hills'],['Pachamalai Hills','hills'],['Meghamalai','hills'],['Sirumalai Hills, Dindigul','hills'],['Pillar Rocks, Kodaikanal','hills'],["Coaker's Walk, Kodaikanal",'hills'],['Muthupet Mangrove Forest','water'],['Semmozhi Poonga, Chennai','hills'],['Guindy National Park, Chennai','hills'],['Poompuhar Coast','water'],['Nagapattinam Coast','water'],['Karaikal Beach','water'],['Silver Beach, Cuddalore','water'],['Promenade, Pondicherry','water'],['Suchindram Temple, Nagercoil','heritage'],['Bhavani Sangam, Erode','water'],['Amaravathi Dam, Udumalpet','water'],['Pulicat Lake','water'],['Kalvarayan Hills','hills']
].map((x,i)=>({title:x[0],category:x[1],src:`assets/${String(i+1).padStart(2,'0')}.png`}));
const septemberCaptions=[
`Your health changes when you take ownership of the next small decision. Begin with one meal, one walk and one promise you can keep today. Save this and choose yourself again tomorrow.\n\n#DoctorFarmer #HealthOwnership #DailyHabits #SelfDiscipline`,
`The transformation people admire is usually built before sunrise, when nobody is watching. Create a morning routine your future self will thank you for. Share this with someone building quietly.\n\n#MorningRoutine #Consistency #HealthyLifestyle #GrowthMindset #DoctorFarmer`,
`Old patterns feel permanent only because they have been repeated for years. Interrupt one today and make room for a stronger version of you. Comment with the habit you are leaving behind.\n\n#BreakThePattern #BetterHabits #MindsetShift #PersonalGrowth #DoctorFarmer`,
`Great bodies and resilient minds are constructed through ordinary repetitions. Every thoughtful meal and every completed set adds another brick. Save this reminder and keep building.\n\n#FitnessJourney #OneRepAtATime #Discipline #HealthyBody #DoctorFarmer`,
`Action creates momentum long before inspiration arrives. Start imperfectly, stay consistent and let progress become your motivation. Send this to someone waiting for the perfect moment.\n\n#TakeAction #NoMoreWaiting #FitnessMotivation #DailyProgress #DoctorFarmer`,
`A focused hour can change more than a distracted week. Decide what matters, remove one delay and move with purpose today. Save this for the moment procrastination returns.\n\n#ActNow #Focus #Urgency #HealthyHabits #DoctorFarmer`,
`Energy is a limited resource. Protect it from needless arguments, endless scrolling and commitments that pull you away from your wellbeing. Choose where your strength goes.\n\n#ProtectYourEnergy #Wellbeing #MindfulLiving #HealthFirst #DoctorFarmer`,
`The strongest routines do not depend on the day of the week. Choose a standard and honour it even when enthusiasm is low. Tag your accountability partner.\n\n#MondayMindset #ConsistencyWins #Routine #SelfDiscipline #DoctorFarmer`,
`Real discipline is steady, adaptable and stronger than a passing feeling. Train yourself to follow the plan while emotions rise and fall. Save this for a difficult day.\n\n#Discipline #MentalStrength #FitnessMindset #DailyHabits #DoctorFarmer`,
`Ease can quietly charge you with lost time, declining energy and delayed dreams. Choose useful discomfort now for greater freedom later. What challenge will you accept today?\n\n#LeaveComfortZone #Growth #HealthyChoices #Motivation #DoctorFarmer`,
`Nature responds to preparation, not negotiation—and the body works the same way. Respect sleep, movement and nourishment as daily essentials. Share this health reminder.\n\n#HealthDiscipline #BodyCare #Wellness #HealthyRoutine #DoctorFarmer`,
`Exhaustion is sometimes a signal to rest, but inconsistency can also make every task feel heavier. Recover honestly, then return to your routine with intention. Save this balanced reminder.\n\n#RestAndReset #Consistency #SelfAwareness #WellnessJourney #DoctorFarmer`,
`A strong future grows from modest actions repeated with care. Never underestimate a short walk, a simple meal or an earlier bedtime. Plant one better habit today.\n\n#SmallHabits #BigResults #HealthyFuture #DailyWellness #DoctorFarmer`,
`Uncertainty does not mean you must stop. Keep taking the next visible step until clarity catches up with your effort. Send this to someone navigating a difficult season.\n\n#KeepGoing #Clarity #Resilience #GrowthMindset #DoctorFarmer`,
`Healthy change needs patience before proof appears. Keep watering the routine even when results are still beneath the surface. Save this and trust your process.\n\n#TrustTheProcess #HealthyHabits #Patience #FitnessJourney #DoctorFarmer`,
`Strength is not the absence of difficult weather; it is the ability to stay grounded through it. Build routines that hold you steady when life becomes unpredictable.\n\n#StayStrong #Resilience #MentalFitness #Discipline #DoctorFarmer`,
`Progress begins just beyond the point where comfort asks you to retreat. Take one safe, meaningful step toward the challenge you have been avoiding. Share this with a brave friend.\n\n#ChooseGrowth #Courage #PersonalDevelopment #HealthyMindset #DoctorFarmer`,
`Visible success depends on invisible foundations. Strengthen sleep, nutrition, movement and mental health before chasing shortcuts. Save this foundation checklist.\n\n#StrongFoundation #HolisticHealth #SleepNutritionMovement #DoctorFarmer`,
`A full calendar still needs space for your wellbeing. Protect a small appointment with yourself today and treat it as seriously as any meeting. When is your health hour?\n\n#MakeTimeForHealth #UrbanWellness #SelfCare #HealthySchedule #DoctorFarmer`,
`Your surroundings may be demanding, but your standards can still survive. Keep a simple routine that works even on noisy, crowded and difficult days. Save it for your busiest week.\n\n#UrbanHealth #WildDiscipline #Routine #HealthyLiving #DoctorFarmer`,
`History reminds us that even powerful things can disappear. Let the habits holding you back end here, and carry only what strengthens your future.\n\n#LetGo #NewBeginning #MindsetReset #PersonalGrowth #DoctorFarmer`,
`Professionals honour the work even when the feeling is absent. Treat your wellbeing with the same responsibility: prepare, show up and complete the task. Tag someone dependable.\n\n#ShowUpDaily #WorkEthic #HealthCommitment #Discipline #DoctorFarmer`,
`Most progress happens away from applause. Keep doing the early, repetitive and unglamorous work until the outcome introduces you. Save this for tomorrow morning.\n\n#UnseenWork #EarlyMorning #Consistency #Results #DoctorFarmer`,
`A clear direction makes a large challenge manageable. Choose one path, remove distractions and take the next step without comparing lanes.\n\n#StayInYourLane #Focus #DailyProgress #Mindset #DoctorFarmer`,
`Consistency has a rhythm that continues through changing emotions. Build a routine simple enough to repeat and strong enough to carry you forward. Share this with your routine partner.\n\n#RoutineMatters #Consistency #CoastalMindset #HealthyHabits #DoctorFarmer`,
`The body you respect is built through devotion to daily practices, not occasional intensity. Approach food, movement and recovery with patience and sincerity.\n\n#BodyRespect #DedicatedLiving #FitnessDiscipline #HealthJourney #DoctorFarmer`,
`Wellbeing improves when its essential parts flow together. Align restorative sleep, nourishing food and regular movement instead of fixing only one piece. Save this three-part plan.\n\n#SleepFoodMovement #BalancedHealth #WellnessPlan #DoctorFarmer`,
`Recovery is productive when it prepares you to return stronger. Schedule rest before exhaustion forces it, and protect your capacity for what matters.\n\n#StrategicRest #Recovery #EnergyManagement #HealthyLifestyle #DoctorFarmer`,
`Sometimes growth requires changing the environment around you. Seek people, places and routines that support the person you are becoming. What condition will you improve first?\n\n#HealthyEnvironment #ChooseBetter #GrowthConditions #DoctorFarmer`,
`A meaningful climb begins with a chosen destination and deliberate direction. Define your health goal, map the habits and keep driving forward one day at a time.\n\n#HealthGoals #IntentionalLiving #DailyDiscipline #DoctorFarmer`
];
const augustPosters=[
 ['Vandalur Zoo, Chennai','hills','assets/august-26.png'],
 ['Tiruparankundram Murugan Temple, Madurai','heritage','assets/august-27.png'],
 ['Kottai Mariamman Temple, Salem','heritage','assets/august-28.png'],
 ['Sathanur Dam, Tiruvannamalai district','water','assets/august-29.png'],
 ['Sittanavasal Cave, Pudukkottai','heritage','assets/august-30.png'],
 ['Yercaud Lake, Salem district','water','assets/august-31.png']
].map(x=>({title:x[0],category:x[1],src:x[2]}));
const augustCaptions=[
`A calmer morning is not an empty morning. Move with intention, protect your attention and let a steady beginning shape the rest of your day.\n\n#DoctorFarmer #CalmMorning #MindfulLiving`,
`The strongest foundations are rarely rushed. Give your health the patience, repetition and care required to last for generations.\n\n#DoctorFarmer #Patience #HealthyHabits`,
`Real strength grows through honest effort repeated quietly. You do not need a perfect day—only one meaningful action you can complete today.\n\n#DoctorFarmer #DailyEffort #Consistency`,
`Calm is not weakness; it is stored power. Pause before reacting, choose what deserves your energy and move with clarity.\n\n#DoctorFarmer #FindYourCalm #MentalWellbeing`,
`Time honours what is built with care. Choose one habit today that your future self will be grateful to inherit.\n\n#DoctorFarmer #BuildToday #HealthyFuture`,
`A peaceful morning is another chance to begin well. Receive it fully, breathe deeply and choose a pace you can sustain.\n\n#DoctorFarmer #MorningGift #Wellbeing`
];
const octoberLocations=[
 ['Thiruvanaikaval Jambukeswarar Temple, Trichy','heritage'],['Kallanai Grand Anicut Dam, Trichy','water'],['Vaitheeswaran Koil, Nagapattinam','heritage'],['Thirumayam Fort, Pudukkottai','heritage'],['Alagar Kovil, Madurai','heritage'],['Manimutharu Falls, Tirunelveli','water'],['Agasthiyar Falls, Tirunelveli','water'],['Srivilliputhur Andal Temple','heritage'],['Nellaiappar Temple, Tirunelveli','heritage'],['Manapad Beach, Thoothukudi','water'],['Vattakottai Fort, Kanyakumari','heritage'],['Sivagangai Palace','heritage'],['Ramanathaswamy Temple, Rameswaram','heritage'],['Sathuragiri Hills, Virudhunagar','hills'],['Swamimalai Temple, Thanjavur','heritage'],['Nagore Dargah, Nagapattinam','heritage'],['Marina Lighthouse, Chennai','water'],['Ennore Creek, Chennai','water'],['Five Rathas, Mahabalipuram','heritage'],['Tiger Cave, Saluvankuppam','heritage'],['Muttukadu Backwaters, ECR','water'],['DakshinaChitra, Chennai','heritage'],['Krishnagiri Dam','water'],['Theerthamalai Hills, Dharmapuri','hills'],['Thiruporur Murugan Temple','heritage'],['Ekambareswarar Temple, Kanchipuram','heritage'],['Uthiramerur Heritage Village','heritage'],['Nagalapuram Falls','water'],['Osudu Lake, Pondicherry region','water'],['Yanaimalai, Madurai','hills'],['Manjolai Hills, Tirunelveli','hills']
];
const octoberPosters=octoberLocations.map((x,i)=>({title:x[0],category:x[1],src:`assets/october-${String(i+1).padStart(2,'0')}.png`}));
const octoberCaptions=[
`You do not need to see the entire path before beginning. Take the next honest step, stay patient with the process and trust that steady movement will reveal the way forward.\n\n#DoctorFarmer #TrustYourPath #KeepMoving #HealthyHabits #DailyMotivation`,
`What you build with care becomes strong enough to serve you for years. Give your health a thoughtful foundation through nourishing food, regular movement, deep sleep and consistency.\n\n#DoctorFarmer #BuiltWithCare #StrongFoundation #Wellbeing #HealthyLifestyle`,
`Healing starts before the result appears—it starts when you decide to participate in your own recovery. Show up for yourself today with one nourishing choice.\n\n#DoctorFarmer #HealingJourney #SelfCare #ChooseYourself #HealthyChoices`,
`Every lasting transformation begins with one small decision. Place one strong habit today, repeat it tomorrow and let consistency build the life you want.\n\n#DoctorFarmer #StrongFoundation #DailyHabits #Consistency #BuildYourHealth`,
`Peace is not always found by escaping your life; sometimes it begins by becoming quiet within it. Protect a few calm minutes today and listen to what your body and mind need.\n\n#DoctorFarmer #InnerPeace #MindfulLiving #MentalWellbeing #SlowDown`,
`Small efforts are never wasted when they move in the same direction. Your short walk, balanced meal, extra glass of water and earlier bedtime all add up.\n\n#DoctorFarmer #SmallEfforts #HealthyLifestyle #DailyProgress #Consistency`,
`Stop measuring the entire distance and focus on the next step. Progress becomes manageable when you give your attention only to the action directly in front of you.\n\n#DoctorFarmer #OneStepAtATime #KeepGoing #Progress #DailyDiscipline`,
`You do not have to transform overnight. Reach a little higher than yesterday, celebrate honest improvement and let small wins become your new standard.\n\n#DoctorFarmer #DailyProgress #GrowthMindset #SmallWins #KeepGrowing`,
`A small lamp can change the atmosphere of an entire corridor. Light your day with one disciplined morning choice and let it guide everything that follows.\n\n#DoctorFarmer #MorningDiscipline #HealthyRoutine #StartStrong #DailyHabits`,
`Every sunrise is permission to begin again without carrying yesterday's mistakes. Breathe deeply, reset your intention and make one choice your future self will appreciate.\n\n#DoctorFarmer #BeginAgain #MorningMotivation #FreshStart #HealthyChoices`,
`Strength is built layer by layer through ordinary actions repeated over time. Keep showing up even when the work feels small—those are the days your foundation becomes stronger.\n\n#DoctorFarmer #Consistency #StrongHealth #DailyDiscipline #KeepBuilding`,
`Royalty is not how the morning looks; it is how carefully you treat yourself within it. Begin with water, movement and a few undistracted minutes.\n\n#DoctorFarmer #MorningCare #SelfRespect #HealthyMorning #ChooseYourself`,
`No meaningful goal is completed in a single leap. Give your ambition the dignity of patient, repeated steps and keep walking until effort becomes achievement.\n\n#DoctorFarmer #PatientProgress #DailyGoals #OneStepAtATime #Consistency`,
`Uncertainty may hide the result, but it does not erase the path. Keep walking through difficult days and let consistency carry you beyond what motivation alone can do.\n\n#DoctorFarmer #KeepWalking #Resilience #TrustTheProcess #NeverGiveUp`,
`Wisdom grows through experience, repetition and reflection—one step at a time. Let today's health choice teach tomorrow's stronger version of you.\n\n#DoctorFarmer #StepByStep #HealthyWisdom #DailyLearning #StrongerEveryDay`,
`Peace of mind is not somewhere you finally arrive. Practise it daily through boundaries, rest, movement and attention to what truly matters.\n\n#DoctorFarmer #PeaceOfMind #DailyPractice #MentalWellbeing #HealthyBoundaries`,
`A lighthouse does not run after every ship; it remains steady and keeps shining. Protect your values, maintain your routine and let consistency become your signal.\n\n#DoctorFarmer #StaySteady #Consistency #KeepShining #DailyDiscipline`,
`Stillness is not inactivity; it is space for your next clear decision. Pause without guilt, recover with intention and move when your direction becomes clear.\n\n#DoctorFarmer #IntentionalRest #Clarity #MindfulLiving #Reset`,
`A masterpiece is shaped through patient work, not hurried effort. Build your health slowly enough for the habits to become natural, stable and lasting.\n\n#DoctorFarmer #PatientWork #HealthyHabits #LongTermHealth #Consistency`,
`Strength does not need to announce itself every day. Sometimes it is simply preparing the meal, taking the walk and keeping the promise quietly.\n\n#DoctorFarmer #QuietStrength #ShowUpDaily #KeepYourPromise #HealthyHabits`,
`A gentle pace can still produce meaningful progress when your direction remains clear. Calm does not stop momentum—it helps you move without wasting your energy.\n\n#DoctorFarmer #CalmProgress #Wellbeing #SustainableHealth #KeepMoving`,
`Traditions survive because people care for them repeatedly. Treat your body with that same daily devotion through nourishment, movement and recovery.\n\n#DoctorFarmer #DailyCare #HealthyDevotion #NourishYourself #Recovery`,
`A reservoir stores strength before releasing it. Build your reserves with sleep, nutritious food and restorative pauses before life asks more from you.\n\n#DoctorFarmer #RestoreYourEnergy #HealthyLiving #RestAndRecover #EnergyManagement`,
`The best view belongs to those who continued climbing after the journey became difficult. Keep earning your progress one disciplined step at a time.\n\n#DoctorFarmer #KeepClimbing #FitnessJourney #NeverGiveUp #DailyProgress`,
`Devotion is the willingness to return with care, again and again. Your health deserves that same faithful attention even on ordinary days.\n\n#DoctorFarmer #DailyDevotion #SelfCare #ShowUpDaily #HealthyCommitment`,
`Deep roots create stability through every changing season. Build routines grounded enough to support you when motivation, schedules and circumstances change.\n\n#DoctorFarmer #DeepRoots #Resilience #StrongHabits #HealthyRoutine`,
`Wisdom begins when you slow down enough to listen. Pay attention to what your body, mind and repeated patterns are telling you before they have to shout.\n\n#DoctorFarmer #ListenWithin #MindfulHealth #SelfAwareness #SlowDown`,
`Nature does not force its flow, and neither should sustainable health. Work with your body through patient recovery, consistent movement and a pace you can repeat.\n\n#DoctorFarmer #SustainableHealth #NaturalFlow #Recovery #HealthyPace`,
`Bloom where you are planted instead of waiting for perfect conditions. Work with the life you have today and grow through one small, meaningful action at a time.\n\n#DoctorFarmer #BloomWhereYouAre #DailyGrowth #SmallSteps #Progress`,
`The strongest foundations are built through steady work over time. Choose repeatable progress over sudden intensity and create health that can endure.\n\n#DoctorFarmer #SlowAndSteady #StrongFoundation #Consistency #LongTermHealth`,
`As this month ends, let your effort continue instead of starting over. Carry the habits that strengthened you, leave the excuses behind and keep building forward.\n\n#DoctorFarmer #CarryForward #NoExcuses #KeepBuilding #MonthlyReset`
];
const novemberLocations=[
 ['Thanjavur Palace & Saraswathi Mahal Library','heritage'],['Perur Pateeswarar Temple, Coimbatore','heritage'],['Parvathamalai','hills'],['Kilakarai Coast','water'],['Keeladi','heritage'],['Arcot Nawab’s Tomb','heritage'],['Kasi Viswanathar Temple, Tenkasi','heritage'],['Thyagaraja Temple, Thiruvarur','water'],['Mayuranathaswami Temple','water'],['Vedaranyam Salt Flats','water'],['Neyveli Township Lake','water'],['Fort St David, Cuddalore','heritage'],['Villupuram Countryside','hills'],['Bhavanisagar Dam','water'],['Chennimalai Murugan Temple','hills'],['Sankagiri Fort','heritage'],['Mettur Dam','water'],['Chitteri Hills','hills'],['Rayakottai Fort','heritage'],['Bargur Hills','hills'],['Gomukhi Dam','water'],['Thirukoilur','water'],['Poondi Reservoir','water'],['Veeraraghava Perumal Temple','heritage'],['Red Hills Lake','water'],['Chembarambakkam Lake','water'],['Neelankarai Beach','water'],['Marundeeswarar Temple','heritage'],['Amirthi Zoological Park','hills'],['Jalakandapuram Falls','water']
];
const novemberPosters=novemberLocations.map((x,i)=>({title:x[0],category:x[1],src:`assets/november-${String(i+1).padStart(2,'0')}.png`}));
const novemberCaptions=[
`A stronger future is built through ordinary days of learning and showing up. Give today your full attention, then return tomorrow ready to grow again.\n\n#DoctorFarmer #KeepLearning #DailyGrowth #Consistency #ShowUpDaily`,
`Make space for the habits that restore and strengthen you. Patient, repeated care can shape a routine that supports you for years.\n\n#DoctorFarmer #MakeTimeForYou #HealthyRoutine #Patience #SelfCare`,
`A difficult path still moves you forward. Focus on the next manageable step and let each honest effort become proof that you are progressing.\n\n#DoctorFarmer #KeepMoving #OneStepAtATime #Progress #Resilience`,
`Stepping back is not always giving up; sometimes it is how you recover your strength. Rest with intention, reset and return ready.\n\n#DoctorFarmer #ComeBackStronger #RestAndRecover #Resilience #KeepGoing`,
`Quiet work may go unnoticed today, but consistency leaves evidence. Keep building habits your future self will be proud to discover.\n\n#DoctorFarmer #QuietProgress #BuildYourFuture #Consistency #DailyHabits`,
`Purpose turns ordinary days into a meaningful life. Treat today's small choices as the building blocks of the legacy you want to leave.\n\n#DoctorFarmer #LiveWithPurpose #DailyChoices #MeaningfulLife #Legacy`,
`Lasting change grows from steady devotion, not occasional intensity. Return to your health with patience and care, especially on ordinary days.\n\n#DoctorFarmer #SteadyDevotion #HealthyCommitment #Consistency #Wellbeing`,
`Calm and strength can exist together. Slow your breathing, clear the noise and choose your next action from a grounded place.\n\n#DoctorFarmer #CalmStrength #MindfulLiving #MentalWellbeing #InnerPeace`,
`Forward does not have to mean fast. Keep moving at a pace you can sustain and trust consistency to carry you farther than urgency.\n\n#DoctorFarmer #KeepMovingForward #SustainableHealth #Consistency #Progress`,
`Simple work becomes powerful when it is repeated with purpose. Do the small healthy things well today and let them leave a lasting mark.\n\n#DoctorFarmer #PurposefulLiving #SmallSteps #HealthyHabits #DailyDiscipline`,
`Healthy growth cannot be rushed. Build your routine thoughtfully, give it time and let steady improvement become part of who you are.\n\n#DoctorFarmer #PlannedGrowth #HealthyRoutine #LongTermHealth #Consistency`,
`What is built with care can withstand difficult seasons. Strengthen your foundation through sleep, nourishment, movement and recovery.\n\n#DoctorFarmer #BuiltWithCare #StrongFoundation #HealthyLifestyle #Resilience`,
`Your season does not need to look like anyone else's. Keep tending your habits with patience and trust that faithful effort will produce its harvest.\n\n#DoctorFarmer #TrustYourSeason #PatientProgress #NoComparison #KeepGrowing`,
`Protect your energy as carefully as you spend it. Rest, boundaries and thoughtful choices help you remain strong through every season.\n\n#DoctorFarmer #ProtectYourEnergy #HealthyBoundaries #RestAndRecover #Wellbeing`,
`The challenge will not shrink, but you can grow stronger with every step. Keep climbing and let disciplined action carry you upward.\n\n#DoctorFarmer #KeepClimbing #OneStepAtATime #Discipline #StrongerEveryDay`,
`Real strength is constructed through patient repetition. Keep laying down one healthy choice at a time, even when progress feels slow.\n\n#DoctorFarmer #BuildStrength #Patience #Consistency #HealthyChoices`,
`Big results begin with one small contribution. Let today's walk, meal or early bedtime become the first drop in a healthier life.\n\n#DoctorFarmer #SmallBeginnings #DailyProgress #HealthyHabits #StartToday`,
`Doubt rarely disappears all at once. Keep moving through the uncertainty and allow each completed step to make the way clearer.\n\n#DoctorFarmer #MoveThroughDoubt #KeepGoing #Courage #Progress`,
`Intentional choices create lasting strength. Build your days around what matters and let your habits become evidence of your priorities.\n\n#DoctorFarmer #LiveIntentionally #StrongHabits #DailyChoices #Purpose`,
`Quiet does not mean weak. Your strength may be growing in the unseen moments when you keep your promises without applause.\n\n#DoctorFarmer #QuietStrength #KeepYourPromise #SelfDiscipline #Consistency`,
`A calm exterior can hold deep strength. Build your inner reserves through rest, reflection and routines that help you stay steady.\n\n#DoctorFarmer #DeepStrength #StayCalm #InnerBalance #HealthyRoutine`,
`Keep moving quietly and let repetition shape the result. Consistent action can carve a lasting change without demanding attention.\n\n#DoctorFarmer #QuietProgress #ConsistentAction #LongTermChange #KeepMoving`,
`The habits that fill your life slowly are often the ones that remain. Choose a pace you can repeat and give change time to settle.\n\n#DoctorFarmer #SlowGrowth #LastingHabits #SustainableHealth #Patience`,
`You do not need to announce every effort. Keep showing up, stay consistent and allow the result to speak for the work you did in silence.\n\n#DoctorFarmer #ShowUpDaily #LetResultsSpeak #Consistency #QuietWork`,
`A steady morning can support an entire day. Begin with simple choices you can trust: hydrate, move, breathe and nourish yourself well.\n\n#DoctorFarmer #MorningRoutine #StartSteady #HealthyMorning #DailyHabits`,
`Discipline does not need noise to be powerful. Keep the promises you make to yourself and let quiet consistency deepen your strength.\n\n#DoctorFarmer #QuietDiscipline #SelfTrust #Consistency #StrongHabits`,
`A setback can become the beginning of your return. Regroup, learn what you need and come back with greater clarity and strength.\n\n#DoctorFarmer #ReturnStronger #Resilience #BeginAgain #KeepGoing`,
`Healing begins in the small choices repeated each morning. Give your body one supportive action today and build from there.\n\n#DoctorFarmer #HealingChoices #MorningHabits #SelfCare #HealthyLiving`,
`Growth does not need to hurry. Give your habits time, nourish them with repetition and trust the strength developing beneath the surface.\n\n#DoctorFarmer #GrowSlowly #HealthyHabits #Patience #Consistency`,
`Do not leave your progress behind when the calendar changes. Carry forward what strengthened you and let steady effort keep flowing.\n\n#DoctorFarmer #CarryItForward #MonthlyReset #KeepBuilding #Consistency`
];
const decemberLocations=[
 ['Sankarankoil Temple, Tenkasi district','heritage'],['Kalugumalai Rock Temple & Vettuvan Koil','heritage'],['Thirparappu Falls, Kanyakumari','water'],['Mathur Aqueduct, Kanyakumari','heritage'],['Chitharal Jain Monument, Kanyakumari','heritage'],['Muttom Beach, Kanyakumari','water'],['Adikesava Perumal Temple, Thiruvattar','heritage'],['Monkey Falls, Pollachi','water'],['Thirumoorthy Dam, Udumalpet','water'],['Siruvani Falls, Coimbatore','water'],['Isha Yoga Center, Coimbatore','heritage'],['Ukkadam Lake, Coimbatore','water'],['Thirumalai Nayakkar Palace, Madurai','heritage'],['Vandiyur Mariamman Teppakulam, Madurai','water'],['Samanar Hills, Madurai','heritage'],['Pykara Falls, Ooty','water'],['Avalanche Lake, Ooty','water'],['Kalhatty Falls, Ooty','water'],['Berijam Lake, Kodaikanal','water'],['Silver Cascade Falls, Kodaikanal','water'],['Guna Caves, Kodaikanal','hills'],['Dindigul Fort','heritage'],['Kamarajar Lake, Dindigul','water'],['Ardhanareeswarar Temple, Tiruchengode','heritage'],['Magudeshwarar Temple, Kodumudi','heritage'],['Kanjamalai Hill, Salem','hills'],['Hosur Countryside, Krishnagiri district','hills'],['Thally Hills, Krishnagiri','hills'],['Pennagaram, Dharmapuri','water'],['VOC Park, Coimbatore','hills'],['Rasipuram, Namakkal district','hills']
];
const decemberPosters=decemberLocations.map((x,i)=>({title:x[0],category:x[1],src:`assets/december-${String(i+1).padStart(2,'0')}.png`}));
const decemberCaptions=[
`A new beginning does not need pressure or noise. Start gently, choose one supportive action and allow steady care to shape the month ahead.\n\n#DoctorFarmer #BeginAgain #GentleStart #HealthyHabits #NewMonth`,
`Patience turns repeated effort into something remarkable. Keep working carefully, trust the process and give your growth the time it deserves.\n\n#DoctorFarmer #Patience #TrustTheProcess #DailyGrowth #Consistency`,
`Sustainable progress comes from steady effort, not exhausted bursts. Find a rhythm you can repeat and let consistency carry you forward.\n\n#DoctorFarmer #SteadyEffort #SustainableHealth #Consistency #KeepGoing`,
`Strong support is built one piece at a time. Strengthen your life through small routines that continue carrying you when motivation changes.\n\n#DoctorFarmer #StrongFoundation #DailyHabits #BuildToLast #Progress`,
`Quiet moments can teach what constant noise hides. Make room to pause, listen inwardly and notice what your body and mind truly need.\n\n#DoctorFarmer #Stillness #ListenWithin #MindfulLiving #InnerPeace`,
`A dependable morning begins by showing up calmly and on time. Create a simple routine that helps you meet each day with clarity.\n\n#DoctorFarmer #MorningRoutine #StartOnTime #DailyDiscipline #HealthyMorning`,
`Your wellbeing deserves faithful attention. Return to nourishing food, movement, rest and self-respect with the same consistency you give your other commitments.\n\n#DoctorFarmer #Wellbeing #SelfCare #Consistency #HealthyCommitment`,
`Healing has its own pace. Give yourself patience, follow the next helpful step and allow progress to unfold without forcing the timeline.\n\n#DoctorFarmer #HealingJourney #BePatient #Recovery #GentleProgress`,
`Saving energy today can become tomorrow's strength. Practise boundaries, protect your rest and spend your attention on what truly matters.\n\n#DoctorFarmer #ProtectYourEnergy #HealthyBoundaries #RestAndRecover #Strength`,
`The best habits form slowly enough to become natural. Repeat simple choices with care until they become part of how you live.\n\n#DoctorFarmer #LastingHabits #SlowGrowth #Consistency #HealthyLifestyle`,
`A few quiet minutes can make the rest of your day easier to carry. Begin with stillness, breathe deeply and choose your direction deliberately.\n\n#DoctorFarmer #MorningStillness #MindfulMorning #CalmMind #DailyPractice`,
`Calm helps you see clearly. Pause before reacting, settle your thoughts and let a quieter mind reveal the wisest next step.\n\n#DoctorFarmer #CalmMind #Clarity #MentalWellbeing #MindfulLiving`,
`Vision becomes lasting progress when it is supported by action. Build toward the future carefully, one disciplined decision at a time.\n\n#DoctorFarmer #BuildWithVision #DailyDiscipline #LongTermGoals #Progress`,
`Large goals become possible through small contributions. Add one useful action today and trust repeated effort to fill the distance.\n\n#DoctorFarmer #OneDropAtATime #SmallSteps #Consistency #BigGoals`,
`A simple life still requires discipline. Keep the routines that matter, remove unnecessary noise and let consistent choices leave their mark.\n\n#DoctorFarmer #SimpleLiving #Discipline #IntentionalLife #HealthyHabits`,
`Forward progress can follow a winding path. Stay committed through the turns and keep choosing the next step that moves you closer.\n\n#DoctorFarmer #KeepMovingForward #TrustYourPath #Resilience #Progress`,
`Rest is not separate from progress; it supports it. Recover without guilt so you can continue the journey with renewed energy and attention.\n\n#DoctorFarmer #RestIsProgress #Recovery #SustainableHealth #SelfCare`,
`A fall does not end your direction. Learn, regain your footing and keep moving toward the life you are working to build.\n\n#DoctorFarmer #RiseAgain #KeepMoving #Resilience #GrowthMindset`,
`Clarity often arrives after the noise becomes quiet. Give yourself undistracted space and listen patiently for the answer already forming within you.\n\n#DoctorFarmer #QuietMind #InnerClarity #Reflection #MentalWellbeing`,
`Small effort can create lasting change when given enough time. Keep flowing in the right direction and let repetition shape the result.\n\n#DoctorFarmer #LastingChange #SmallEfforts #Consistency #KeepGoing`,
`Uncertainty is often an unexplored path. Meet it with curiosity, take the first step and let experience replace fear with understanding.\n\n#DoctorFarmer #FaceTheUnknown #Courage #TakeTheFirstStep #Growth`,
`Nothing strong is built all at once. Honour every small block of progress and keep adding to the foundation with patience.\n\n#DoctorFarmer #BlockByBlock #PatientProgress #StrongFoundation #Consistency`,
`A quiet walk can reset more than your body. Step away from the noise, breathe deeply and give your mind room to settle.\n\n#DoctorFarmer #TakeAWalk #MentalWellbeing #MoveYourBody #ClearYourMind`,
`Balance is a daily practice, not a perfect destination. Adjust, learn and return to the habits that keep your life steady.\n\n#DoctorFarmer #PractiseBalance #DailyWellbeing #HealthyRoutine #MindfulLiving`,
`Whatever today means to you, let gratitude have a place in it. Notice what is good, appreciate who is near and receive the moment fully.\n\n#DoctorFarmer #ChooseGratitude #CelebrateToday #MindfulLiving #Joy`,
`Rest can be the most useful choice when tomorrow needs your best. Recover intentionally and allow your energy to return without guilt.\n\n#DoctorFarmer #RestToday #RecoverWell #EnergyManagement #SelfCare`,
`Every day gives you ground where something meaningful can grow. Plant a helpful habit, nourish it with repetition and protect it with patience.\n\n#DoctorFarmer #PlantGoodHabits #DailyGrowth #HealthyChoices #Consistency`,
`The higher you climb, the more clearly you understand the journey. Keep doing the difficult work and let perspective arrive through progress.\n\n#DoctorFarmer #KeepClimbing #GainPerspective #Progress #Resilience`,
`The final days still matter. Use them with intention, complete one meaningful promise and finish the year knowing you kept moving.\n\n#DoctorFarmer #FinishStrong #MakeTodayCount #KeepYourPromise #YearEnd`,
`Look back to recognise your growth, then face forward again. Let past progress strengthen your confidence without becoming a place you stop.\n\n#DoctorFarmer #SeeYourProgress #KeepMovingForward #Growth #Reflection`,
`End this year without rushing or judging yourself. Carry forward the habits that helped you and enter the next chapter with quiet resolve.\n\n#DoctorFarmer #YearEndReflection #QuietResolve #CarryForward #NewBeginning`
];
let posters=septemberPosters,captions=septemberCaptions;
const calendar=document.querySelector('#calendar'),collectionContent=document.querySelector('#collection-content'),channelDashboard=document.querySelector('#channel-dashboard'),contentTypePage=document.querySelector('#content-type-page'),contentTypeTitle=document.querySelector('#content-type-title'),channelWorkspace=document.querySelector('#channel-workspace'),emptyChannel=document.querySelector('#empty-channel'),emptyChannelTitle=document.querySelector('#empty-channel-title'),emptyChannelNote=document.querySelector('#empty-channel-note'),videoCarouselPage=document.querySelector('#video-carousel-page'),videoCarouselGrid=document.querySelector('#video-carousel-grid'),formatEmptyPage=document.querySelector('#format-empty-page'),formatEmptyTitle=document.querySelector('#format-empty-title'),formatBrand=document.querySelector('#format-brand'),formatBack=document.querySelector('#format-back'),channelReady=document.querySelector('#channel-ready'),channelReadyGrid=document.querySelector('#channel-ready-grid'),emptyMonthGrid=document.querySelector('#empty-month-grid'),startInput=document.querySelector('#start-date'),viewer=document.querySelector('#viewer'),viewerImage=document.querySelector('#viewer-image'),viewerTitle=document.querySelector('#viewer-title'),viewerCount=document.querySelector('#viewer-count'),viewerCaption=document.querySelector('#viewer-caption'),viewerDate=document.querySelector('#viewer-date'),viewerLocation=document.querySelector('#viewer-location'),viewerAvatar=document.querySelector('#viewer-avatar'),viewerCaptionAvatar=document.querySelector('#viewer-caption-avatar'),viewerUsername=document.querySelector('#viewer-username'),viewerAppointment=document.querySelector('#viewer-appointment'),copyCaptionButton=document.querySelector('.copy-caption');
const fofitosPosts=[
 {title:'Berry Crunch Overnight Oats',src:'assets/fofitos/berry-crunch-oats.png',date:'2026-08-25',emoji:'🥣🍓',heading:'Better Breakfast. Honest Ingredients.',description:'Colourful berries, creamy oats and balanced goodness come together in every satisfying layer.',claims:['🌾 Fibre That Delivers — 7.2 g per serving','💪 Protein in Every Layer — 9.9 g per serving']},
 {title:'Watermelon Mint Chia Cooler',src:'assets/fofitos/watermelon-melon.png',date:'2026-08-26',emoji:'🍉🌿',heading:'Cool, Fresh and Made to Refresh.',description:'Juicy watermelon, fresh mint and chia create a light cooler made for bright, refreshing moments.',claims:['✨ Light Refreshment — 138.9 kcal','🌱 Chia Fibre Boost — 2.5 g']},
 {title:'South Indian Paneer Rice Bowl',src:'assets/fofitos/south-indian-paneer.png',date:'2026-08-27',emoji:'🍚🧀',heading:'South Indian Comfort. Balanced Goodness.',description:'Paneer, wholesome rice and colourful vegetables make this bowl hearty, satisfying and full of flavour.',claims:['💪 Paneer Power — 20 g protein','🌾 Fibre-Forward — 8.2 g']},
 {title:'Go Right Way Burger',src:'assets/fofitos/burger-go-right.png',date:'2026-08-28',emoji:'🍔🚦',heading:'When Hunger Hits, Go the Right Way.',description:'A bold burger layered with satisfying flavour, fresh crunch and protein for an exciting meal break.',claims:['💪 Protein on the Go — 30.8 g','🌾 Fibre in the Bite — 4.7 g']},
 {title:'FOFiTOS Bowl Collection',src:'assets/fofitos/bowls-collection.png',date:'2026-08-29',emoji:'🥗🍚',heading:'Four Bowls. Four Honest Choices.',description:'From paneer to chicken, every colourful bowl delivers its own mix of flavour, texture and balanced satisfaction.',claims:['💪 20 g+ Protein Choices','🌾 6 g+ Fibre Choices']},
 {title:'Seoul Korean Chicken Roll',src:'assets/fofitos/korean-chicken-wrap.png',date:'2026-08-30',emoji:'🌯🔥',heading:'Korean Flavour, Rolled Fresh.',description:'Sweet heat, savoury chicken and fresh layers come together in a wrap built for bold cravings.',claims:['💪 Protein-Packed — 31.4 g','⚡ Balanced Bite — 337.7 kcal']},
 {title:'Fresh Cooler Trio',src:'assets/fofitos/beverages-trio.png',date:'2026-08-31',emoji:'🍊🍉',heading:'Three Fresh Ways to Cool Down.',description:'Choose a fruity orange cooler, watermelon refreshment or comforting masala buttermilk.',claims:['🍊 Orange — 7.5 g fibre','🍉 Watermelon — 138.9 kcal','🥛 Chaas — 62.2 kcal']},
 {title:'Tex Mex Chicken Crunch Sandwich',src:'assets/fofitos/tex-mex-sandwich.png',date:'2026-09-01',emoji:'🥪🌮',heading:'Tex-Mex Crunch in Every Bite.',description:'Toasted bread, bold Tex-Mex chicken and fresh layers make every bite colourful and satisfying.',claims:['💪 Protein with Crunch — 20.3 g','🌾 Fibre-Forward — 5.1 g']},
 {title:'Smoky Chicken Tikka Bowl',src:'assets/fofitos/smoky-tikka-bowl.png',date:'2026-09-02',emoji:'🥗🔥',heading:'Smoky, Colourful and Protein-Powered.',description:'Smoky chicken tikka meets crisp vegetables and vibrant toppings in one complete, flavour-packed bowl.',claims:['💪 Protein-Powered — 29.1 g','🌾 Fibre-Forward Fuel — 7.8 g']},
 {title:'Spicy Peri Peri Paneer Burger',src:'assets/fofitos/spicy-paneer-burger.png',date:'2026-09-03',emoji:'🍔🌶️',heading:'Turn Up the Paneer Power.',description:'Spicy peri peri paneer, crisp greens and a soft bun deliver a meat-free burger with bold character.',claims:['💪 Paneer Protein Punch — 21.5 g','🌾 Fibre in the Flavour — 6 g']},
 {title:'South Indian Red Rice Bowl',src:'assets/fofitos/south-indian-red-rice.png',date:'2026-09-04',emoji:'🍚🌱',heading:'Whole-Grain Comfort in Every Bowl.',description:'Red rice, rich curry and fresh vegetables come together in a colourful South Indian-inspired meal.',claims:['🌾 Whole-Grain Goodness','🌱 Plant-Powered Bowl']},
 {title:'Healthy Bowl Face-Off',src:'assets/fofitos/healthy-bowl-choice.png',date:'2026-09-05',emoji:'🥗🍉',heading:'Two Bowls. Your Kind of Healthy.',description:'Choose savoury Korean chicken power or a bright mixed-fruit bowl—both made with fresh, colourful ingredients.',claims:['🍗 Chicken Power — 31.3 g protein','🍉 Fruit Fibre — 5.7 g']},
 {title:'Peri Peri Chicken Burger',src:'assets/fofitos/peri-peri-chicken-burger.png',date:'2026-09-06',emoji:'🍔🔥',heading:'Hot, Delicious and Protein-Powered.',description:'Grilled peri peri chicken, fresh crunchy layers and bold flavour come together in a burger made to earn its place on your plate.',claims:['💪 Protein-Powered — 33.5 g per serving','🌾 Fibre in Every Bite — 6 g per serving']},
 {title:'Chicken Tikka Burger',src:'assets/fofitos/chicken-tikka-burger.png',date:'2026-09-07',emoji:'🍔🔥',heading:'Tikka Flavour. Serious Protein.',description:'Smoky chicken tikka, fresh lettuce, onion and creamy layers stack up into a burger built for real cravings.',claims:['💪 Protein Packed — 30.8 g','⚡ Big Flavour — 392.5 kcal']},
 {title:'Basil Pesto Chicken Bowl',src:'assets/fofitos/basil-pesto-chicken-bowl.png',date:'2026-09-08',emoji:'🥗🌿',heading:'Green, Fresh and Protein-Powered.',description:'Basil pesto chicken, avocado, greens and sweet potato create a colourful bowl with balance in every bite.',claims:['💪 Protein Power — 30.3 g','🌾 Fibre Rich — 7.1 g']},
 {title:'Tex-Mex Paneer Bowl',src:'assets/fofitos/tex-mex-paneer-bowl.png',date:'2026-09-09',emoji:'🥣🌮',heading:'Tex-Mex Energy, Paneer Style.',description:'Paneer, salsa, corn, rice and guacamole bring bold colour and satisfying texture to one complete bowl.',claims:['💪 Powered By — 17.8 g protein','🌾 Fibre That Fills — 6.6 g']},
 {title:'All Set to Eat Bowl Collection',src:'assets/fofitos/all-set-to-eat.png',date:'2026-09-10',emoji:'🥗🍚',heading:'Three Bowls. Plenty of Good Choices.',description:'A colourful line-up of freshly made bowls gives every craving a balanced, flavour-packed answer.',claims:['💪 Protein Choices — 20 g+','🌾 Fibre-Rich Picks — 6 g+']},
 {title:'Balanced Rice Bowls',src:'assets/fofitos/balanced-rice-bowls.png',date:'2026-09-11',emoji:'🍚🥦',heading:'Balanced Bowls, Bold Personalities.',description:'Basil pesto, South Indian comfort and Tex-Mex flavour make healthy meals anything but repetitive.',claims:['💪 Protein Choices — 20 g+','🌾 Fibre Picks — 6.7 g+']},
 {title:'Watermelon Chia Refreshment',src:'assets/fofitos/watermelon-refreshment.png',date:'2026-09-12',emoji:'🍉🧊',heading:'Cool Colour. Light Refreshment.',description:'Watermelon, mint, chia and plenty of ice make this a bright sip for warm Chennai days.',claims:['✨ Refreshingly Light — 138.9 kcal','🌱 Chia Fibre — 2.5 g']},
 {title:'Hungry to Healthy Chicken Bowl',src:'assets/fofitos/hungry-to-healthy.png',date:'2026-09-13',emoji:'🥗💜',heading:'From Hungry to Healthy.',description:'Smoky chicken, avocado, broccoli and colourful vegetables turn one bowl into a satisfying reset.',claims:['💪 Protein Power — 29.1 g','🌾 Fibre That Fills — 7.8 g']},
 {title:'Endless Delight Drinks',src:'assets/fofitos/endless-delight-drinks.png',date:'2026-09-14',emoji:'🥤🍉',heading:'Three Drinks. Three Refreshing Moods.',description:'Masala chaas, orange mint chia and watermelon basil chia bring a different kind of freshness to every sip.',claims:['🥛 Light Sip — 62.2 kcal','🍊 Fibre Rich — 7.5 g','🍉 Fruity Refresh — 138.9 kcal']},
 {title:'Tex-Mex Burrito Bowl Duo',src:'assets/fofitos/burrito-bowl-duo.png',date:'2026-09-15',emoji:'🥣🌮',heading:'Choose Your Tex-Mex Power.',description:'Paneer and chicken burrito bowls deliver the same bold Tex-Mex character with two satisfying protein choices.',claims:['🧀 Paneer Power — 17.8 g protein','🍗 Chicken Power — 26.5 g protein']},
 {title:'Chicken Rainbow Bowl',src:'assets/fofitos/chicken-rainbow-v2.png',date:'2026-09-16',emoji:'🌈🥗',heading:'Eat the Rainbow. Feel Amazing.',description:'Chicken, avocado, greens and vibrant vegetables make this bowl as satisfying as it is colourful.',claims:['💪 Protein Packed — 30.8 g','🌾 Fibre Rich — 8.8 g']}
];
const fofitosCaptions=[
 `🥣🍓 Layer by Layer, We Do It Better.\n\nBreakfast should taste exciting and still give you something worthwhile.\n\nBerry Crunch Overnight Oats brings creamy oats, colourful berries and a satisfying crunch together in every spoonful.\n\n🌾 Fibre that delivers — 7.2 g per serving\n💪 Protein in every layer — 9.9 g per serving\n🍓 Freshly sourced, perfectly paired\n\nGood ingredients. Better mornings. Nothing hidden.\n\n💜 FOFITOS — Nothing To Hide.\n\n📲 Available now on Swiggy & Zomato.\n\n👇 Would you choose this for breakfast or dessert?\n\n#FOFITOS #NothingToHide #BerryCrunch #OvernightOats #BreakfastIdeas #RealFood #FreshIngredients #ChennaiFoodie #Porur #Kattupakkam #Swiggy #Zomato`,
 `🍉🌿 Refreshment That Actually Feels Fresh.\n\nSome days call for something light, cool and naturally colourful.\n\nWatermelon Mint Chia Cooler brings juicy watermelon, cooling mint and chia together for an easy, refreshing sip.\n\n✨ Light refreshment — 138.9 kcal\n🌱 Chia fibre boost — 2.5 g\n🧊 Cool, fruity and made to refresh\n\nNo heavy feeling. Just a brighter break in your day.\n\n💜 FOFITOS — Nothing To Hide.\n\n📲 Available now on Swiggy & Zomato.\n\n👇 Who needs this cooler today?\n\n#FOFITOS #NothingToHide #WatermelonCooler #ChiaDrink #FreshDrinks #SummerRefreshment #RealIngredients #ChennaiFoodie #Porur #Kattupakkam #Swiggy #Zomato`,
 `🍚🧀 South Indian Comfort, Built into One Bowl.\n\nA satisfying meal does not need to be complicated. It just needs the right balance of flavour, texture and honest ingredients.\n\nThis bowl brings paneer, wholesome rice and colourful vegetables together for comforting goodness in every bite.\n\n💪 Paneer power — 20 g protein\n🌾 Fibre-forward — 8.2 g\n🥦 Colourful vegetables, complete satisfaction\n\nComfort food can still be thoughtfully made.\n\n💜 FOFITOS — Nothing To Hide.\n\n📲 Available now on Swiggy & Zomato.\n\n👇 Are you choosing paneer for lunch or dinner?\n\n#FOFITOS #NothingToHide #PaneerRiceBowl #SouthIndianFood #ProteinMeal #RiceBowl #RealFood #FreshIngredients #ChennaiFoodie #Porur #Swiggy #Zomato`,
 `🍔🚦 When Hunger Hits, Go the Right Way.\n\nNot every burger deserves a place on your plate. This one earns it with bold flavour and a genuinely satisfying bite.\n\nFresh layers, a flavour-packed centre and the right amount of crunch make it more than an ordinary burger break.\n\n💪 Protein on the go — 30.8 g\n🌾 Fibre in the bite — 4.7 g\n🥬 Fresh layers. Real flavour.\n\nNo gimmicks. No forgettable bites. Just a burger worth coming back for.\n\n💜 FOFITOS — Nothing To Hide.\n\n📲 Available now on Swiggy & Zomato.\n\n👇 One word to describe your perfect burger?\n\n#FOFITOS #NothingToHide #BurgerGoals #ProteinBurger #RealFood #FreshIngredients #ChennaiFoodie #WholeWheat #Porur #Kattupakkam #Swiggy #Zomato`,
 `🥗🍚 One Menu. Four Bowls. Plenty of Good Choices.\n\nHealthy eating should never feel like choosing the same meal again and again.\n\nFrom paneer to chicken, every FOFITOS bowl brings its own combination of colour, texture and bold flavour.\n\n💪 20 g+ protein choices\n🌾 6 g+ fibre choices\n🥦 Fresh vegetables across every bowl\n\nDifferent cravings. The same honest approach to food.\n\n💜 FOFITOS — Nothing To Hide.\n\n📲 Available now on Swiggy & Zomato.\n\n👇 Which bowl are you trying first?\n\n#FOFITOS #NothingToHide #HealthyBowls #RiceBowl #ProteinMeals #BalancedEating #RealFood #FreshIngredients #ChennaiFoodie #Porur #Swiggy #Zomato`,
 `🌯🔥 Korean Flavour, Rolled Fresh.\n\nWhen you want something quick, your meal should not have to feel ordinary.\n\nThe Seoul Korean Chicken Roll combines savoury chicken, bold Korean-inspired flavour and fresh layers in one satisfying wrap.\n\n💪 Protein-packed — 31.4 g\n⚡ Balanced bite — 337.7 kcal\n🌯 Big flavour in an easy-to-enjoy roll\n\nFast to eat. Hard to forget.\n\n💜 FOFITOS — Nothing To Hide.\n\n📲 Available now on Swiggy & Zomato.\n\n👇 Would this be your lunch or evening meal?\n\n#FOFITOS #NothingToHide #KoreanChicken #ChickenRoll #ProteinPacked #KoreanFood #RealFood #ChennaiFoodie #Porur #Kattupakkam #Swiggy #Zomato`,
 `🍊🍉 Three Coolers. Three Different Moods.\n\nRefreshment should match the moment. Fruity, cooling or comforting—you get to choose.\n\nPick bright orange, juicy watermelon or classic masala chaas for a fresh finish to your meal.\n\n🍊 Orange — 7.5 g fibre\n🍉 Watermelon — 138.9 kcal\n🥛 Chaas — 62.2 kcal\n\nThree refreshing choices. Nothing unnecessary.\n\n💜 FOFITOS — Nothing To Hide.\n\n📲 Available now on Swiggy & Zomato.\n\n👇 Orange, watermelon or chaas?\n\n#FOFITOS #NothingToHide #FreshCoolers #OrangeDrink #WatermelonCooler #MasalaChaas #RefreshingDrinks #RealIngredients #ChennaiFoodie #Porur #Swiggy #Zomato`,
 `🥪🌮 Tex-Mex Crunch That Does More Than Taste Good.\n\nA sandwich can be quick without becoming forgettable.\n\nToasted bread, flavour-packed Tex-Mex chicken and fresh crunchy layers make every bite satisfying from corner to corner.\n\n💪 Protein with crunch — 20.3 g\n🌾 Fibre-forward — 5.1 g\n🥬 Fresh layers in every bite\n\nBold flavour. Honest ingredients. No boring lunch breaks.\n\n💜 FOFITOS — Nothing To Hide.\n\n📲 Available now on Swiggy & Zomato.\n\n👇 Tag someone who always chooses the sandwich.\n\n#FOFITOS #NothingToHide #TexMexChicken #ChickenSandwich #ProteinMeal #WholeWheat #RealFood #FreshIngredients #ChennaiFoodie #Porur #Swiggy #Zomato`,
 `🥗🔥 Smoky Tikka. Fresh Crunch. One Powerful Bowl.\n\nA filling bowl should bring more than quantity. It should bring colour, texture and flavour that keeps every bite interesting.\n\nSmoky chicken tikka meets crisp vegetables and vibrant toppings for a meal built to satisfy.\n\n💪 Protein-powered — 29.1 g\n🌾 Fibre-forward fuel — 7.8 g\n🥦 Colourful vegetables, freshly layered\n\nThis is what a bowl with real character looks like.\n\n💜 FOFITOS — Nothing To Hide.\n\n📲 Available now on Swiggy & Zomato.\n\n👇 Would you finish the chicken or vegetables first?\n\n#FOFITOS #NothingToHide #ChickenTikkaBowl #HealthyBowl #ProteinPowered #FibreRich #BalancedMeal #RealFood #ChennaiFoodie #Porur #Swiggy #Zomato`,
 `🍔🌶️ Paneer Can Handle the Heat.\n\nA meat-free burger should never feel like the backup choice.\n\nSpicy peri peri paneer, fresh greens and a soft bun come together for a burger with real flavour and serious character.\n\n💪 Paneer protein punch — 21.5 g\n🌾 Fibre in the flavour — 6 g\n🔥 Spicy, satisfying and boldly made\n\nNo compromise. Just paneer done properly.\n\n💜 FOFITOS — Nothing To Hide.\n\n📲 Available now on Swiggy & Zomato.\n\n👇 How spicy do you like your burger?\n\n#FOFITOS #NothingToHide #PeriPeriPaneer #PaneerBurger #ProteinBurger #SpicyFood #RealFood #FreshIngredients #ChennaiFoodie #Porur #Swiggy #Zomato`,
 `🍚🌱 Whole-Grain Comfort, South Indian Style.\n\nSome meals feel good because they keep things honest and familiar.\n\nSouth Indian red rice, comforting curry and colourful vegetables come together in a bowl made for satisfying everyday eating.\n\n🌾 Whole-grain goodness\n🌱 Plant-powered bowl\n🥦 Colourful vegetables in every serving\n\nSimple ingredients. Full flavour. A bowl worth slowing down for.\n\n💜 FOFITOS — Nothing To Hide.\n\n📲 Available now on Swiggy & Zomato.\n\n👇 Would this be your comfort-food pick?\n\n#FOFITOS #NothingToHide #RedRiceBowl #SouthIndianFood #WholeGrains #PlantPowered #HealthyEating #RealFood #FreshIngredients #ChennaiFoodie #Swiggy #Zomato`,
 `🥗🍉 Two Bowls. Two Ways to Eat Better.\n\nHealthy does not have to look the same for everyone—or every craving.\n\nChoose a savoury Seoul Korean Chicken Bowl when you want a protein-powered meal, or a colourful fruit bowl when you want something bright and fresh.\n\n🍗 Chicken power — 31.3 g protein\n🍉 Fruit fibre — 5.7 g\n🥝 Fresh colour whichever way you choose\n\nDifferent bowls. The same commitment to honest ingredients.\n\n💜 FOFITOS — Nothing To Hide.\n\n📲 Available now on Swiggy & Zomato.\n\n👇 Team chicken bowl or team fruit bowl?\n\n#FOFITOS #NothingToHide #HealthyChoices #KoreanChickenBowl #FruitBowl #ProteinMeal #FibreRich #RealFood #FreshIngredients #ChennaiFoodie #Swiggy #Zomato`,
 `🍔🔥 Not Every Burger Deserves a Spot on Your Plate. This One Earns It.\n\nThe Peri Peri Chicken Burger is not just about bringing the heat. It is about getting every layer right.\n\nGrilled chicken, fresh crunch and bold peri peri flavour come together in a burger made for serious cravings.\n\n💪 Protein-powered — 33.5 g per serving\n🌾 Fibre in every bite — 6 g per serving\n🥬 Fresh layers. Real flavour.\n\nNo gimmicks. No forgettable bites. Just a burger you will come back for.\n\n💜 FOFITOS — Nothing To Hide.\n\n📲 Available now on Swiggy & Zomato.\n\n👇 One word to describe this burger?\n\n#FOFITOS #NothingToHide #PeriPeriChickenBurger #ProteinBurger #GrilledChicken #BurgerGoals #RealFood #FreshIngredients #ChennaiFoodie #Porur #Kattupakkam #Swiggy #Zomato`,
 `🍔🔥 Tikka Flavour That Stacks Up.\n\nA burger should bring more than size. It should bring flavour, texture and something worth coming back for.\n\nSmoky chicken tikka, fresh lettuce, onion and creamy layers make every bite count.\n\n💪 Protein packed — 30.8 g\n⚡ Big flavour — 392.5 kcal\n🥬 Fresh layers from top to bottom\n\nBold cravings deserve an honest answer.\n\n💜 FOFITOS — Nothing To Hide.\n\n📲 Available now on Swiggy & Zomato.\n\n👇 Who would finish this burger first?\n\n#FOFITOS #NothingToHide #ChickenTikkaBurger #ProteinBurger #BurgerLovers #RealFood #FreshIngredients #ChennaiFoodie #Porur #Kattupakkam #Swiggy #Zomato`,
 `🥗🌿 Green Looks Good on You.\n\nFresh food becomes exciting when every ingredient brings its own colour, texture and purpose.\n\nBasil pesto chicken, avocado, greens and sweet potato come together in one bright, satisfying bowl.\n\n💪 Protein power — 30.3 g\n🌾 Fibre rich — 7.1 g\n🥑 Fresh colour in every bite\n\nBalanced can still be bold.\n\n💜 FOFITOS — Nothing To Hide.\n\n📲 Available now on Swiggy & Zomato.\n\n👇 Would this be your lunch or post-workout meal?\n\n#FOFITOS #NothingToHide #BasilPestoChicken #HealthyBowl #ProteinMeal #FibreRich #FreshFood #ChennaiFoodie #Porur #Kattupakkam #Swiggy #Zomato`,
 `🥣🌮 Paneer Just Took a Tex-Mex Turn.\n\nColour, crunch and bold flavour belong in the same bowl.\n\nPaneer, salsa, corn, rice and guacamole bring a satisfying Tex-Mex mix to every spoonful.\n\n💪 Powered by — 17.8 g protein\n🌾 Fibre that fills — 6.6 g\n🌽 Big colour. Bigger character.\n\nA complete bowl should never feel predictable.\n\n💜 FOFITOS — Nothing To Hide.\n\n📲 Available now on Swiggy & Zomato.\n\n👇 Extra salsa or extra guacamole?\n\n#FOFITOS #NothingToHide #TexMexPaneer #PaneerBowl #BurritoBowl #ProteinMeal #FibreRich #ChennaiFoodie #Porur #Kattupakkam #Swiggy #Zomato`,
 `🥗🍚 All Set to Eat.\n\nDifferent cravings deserve more than one healthy answer.\n\nChoose from colourful bowls loaded with fresh vegetables, satisfying protein and flavour that keeps lunch interesting.\n\n💪 Protein choices — 20 g+\n🌾 Fibre-rich picks — 6 g+\n🥦 Freshly made and loaded with flavour\n\nOne menu. Plenty of honest choices.\n\n💜 FOFITOS — Nothing To Hide.\n\n📲 Available now on Swiggy & Zomato.\n\n👇 Which bowl are you picking today?\n\n#FOFITOS #NothingToHide #HealthyBowls #ProteinChoices #FibreRich #BalancedMeals #FreshIngredients #ChennaiFoodie #Porur #Kattupakkam #Swiggy #Zomato`,
 `🍚🥦 Balance Never Has to Be Boring.\n\nA better meal is one you actually look forward to eating.\n\nBasil pesto, South Indian comfort and Tex-Mex flavour give you three colourful ways to build a satisfying lunch.\n\n💪 Protein choices — 20 g+\n🌾 Fibre picks — 6.7 g+\n🥗 Three bowls. Three bold personalities.\n\nHealthy meals, nothing to hide.\n\n💜 FOFITOS — Nothing To Hide.\n\n📲 Available now on Swiggy & Zomato.\n\n👇 Basil pesto, South Indian or Tex-Mex?\n\n#FOFITOS #NothingToHide #BalancedBowls #RiceBowls #ProteinMeals #FibreRich #HealthyEating #ChennaiFoodie #Porur #Kattupakkam #Swiggy #Zomato`,
 `🍉🧊 The Best Kind of Refreshment Is Here.\n\nBright colour, real fruit and an icy finish can turn an ordinary break into something better.\n\nWatermelon, mint and chia come together for a drink made to cool, refresh and brighten your day.\n\n✨ Refreshingly light — 138.9 kcal\n🌱 Chia fibre — 2.5 g\n🧊 Best served ice-cold\n\nFreshness you can see before the first sip.\n\n💜 FOFITOS — Nothing To Hide.\n\n📲 Available now on Swiggy & Zomato.\n\n👇 Who needs this cooler today?\n\n#FOFITOS #NothingToHide #WatermelonDrink #ChiaCooler #FreshDrinks #SummerRefreshment #RealIngredients #ChennaiFoodie #Porur #Kattupakkam #Swiggy #Zomato`,
 `🥗💜 From Hungry to Healthy in One Bowl.\n\nA satisfying meal can bring comfort and still keep the ingredients colourful and honest.\n\nSmoky chicken, avocado, broccoli and fresh vegetables turn this bowl into a powerful reset.\n\n💪 Protein power — 29.1 g\n🌾 Fibre that fills — 7.8 g\n🥦 Colourful fuel for the day\n\nEat well. Feel ready for what comes next.\n\n💜 FOFITOS — Nothing To Hide.\n\n📲 Available now on Swiggy & Zomato.\n\n👇 What ingredient would you eat first?\n\n#FOFITOS #NothingToHide #HealthyChickenBowl #ProteinPower #FibreRich #BalancedMeal #FreshFood #ChennaiFoodie #Porur #Kattupakkam #Swiggy #Zomato`,
 `🥤🍉 Three Drinks. Endless Delight.\n\nEvery mood deserves its own kind of refreshment.\n\nChoose comforting masala chaas, bright orange mint chia or a fruity watermelon basil chia cooler.\n\n🥛 Light sip — 62.2 kcal\n🍊 Fibre rich — 7.5 g\n🍉 Fruity refresh — 138.9 kcal\n\nThree colours. Three flavours. Nothing hidden.\n\n💜 FOFITOS — Nothing To Hide.\n\n📲 Available now on Swiggy & Zomato.\n\n👇 Which glass are you reaching for?\n\n#FOFITOS #NothingToHide #MasalaChaas #OrangeMintChia #WatermelonChia #FreshDrinks #RefreshingChoices #ChennaiFoodie #Porur #Kattupakkam #Swiggy #Zomato`,
 `🥣🌮 Two Bowls. Two Kinds of Power.\n\nTex-Mex cravings do not have to come with only one choice.\n\nPick paneer for a rich vegetarian bowl or chicken when you want an extra protein push.\n\n🧀 Paneer power — 17.8 g protein\n🍗 Chicken power — 26.5 g protein\n🌽 Bold flavour in both bowls\n\nDifferent proteins. The same honest approach.\n\n💜 FOFITOS — Nothing To Hide.\n\n📲 Available now on Swiggy & Zomato.\n\n👇 Team paneer or team chicken?\n\n#FOFITOS #NothingToHide #BurritoBowl #TexMexBowl #PaneerBowl #ChickenBowl #ProteinChoices #ChennaiFoodie #Porur #Kattupakkam #Swiggy #Zomato`,
 `🌈🥗 Eat the Rainbow. Feel Amazing.\n\nThe best bowls look exciting before the first bite and stay satisfying until the last.\n\nChicken, avocado, greens and colourful vegetables bring freshness, texture and power together.\n\n💪 Protein packed — 30.8 g\n🌾 Fibre rich — 8.8 g\n🥑 Colourful ingredients, complete satisfaction\n\nHealthy food makes everything better.\n\n💜 FOFITOS — Nothing To Hide.\n\n📲 Available now on Swiggy & Zomato.\n\n👇 How many colours can you spot?\n\n#FOFITOS #NothingToHide #ChickenRainbowBowl #EatTheRainbow #ProteinPacked #FibreRich #HealthyBowl #ChennaiFoodie #Porur #Kattupakkam #Swiggy #Zomato`
];
const doctorHashtags='#doctorfarmer #myhealthschool #Consistency #Progress #GrowthMindset #Discipline #SuccessMindset #KeepGoing #PersonalGrowth #Motivation #SelfImprovement #DailyMotivation';
const doctorVideoCarousels=[
 {
  title:'Dr. N. Rajagopal — Award Journey',
  image:'assets/video-carousel/B019C009 250907XY.JPG?v=20260825-3',
  video:'https://drive.usercontent.google.com/download?id=1sgwKQ2oC4Ykl_kqt_DKbnWlDxkIhzVWa&export=download&confirm=t',
  source:'B019C009 250907XY.srt',
  caption:`For appointments:\n+91 89259 54625\n+91 72004 24271\n\nFrom an HbA1c of 9.7 to 5.5, a 12 kg weight reduction, and proudly receiving the award he set as his goal! 🏆 Dr. N. Rajagopal’s journey shows how sincere learning, consistent action, mindset support, and committed guidance can create meaningful progress. ❤️\n\nWatch his inspiring journey and share this with someone who needs hope. 🙌\n\n#doctorfarmer #myhealthschool #diabetes #health #wellness #diabetesmanagement #bloodsugarcontrol #HbA1c #healthylifestyle #diabetesawareness #diabetesjourney #lifestylechanges`,
  videoCaptions:[`HbA1c 9.7 முதல் 5.5 வரை\nஒழுக்கத்தின் வெற்றி`,`12 kg குறைந்தது\nவாழ்க்கையின் இலக்கும் இன்று வென்றது`]
 },
 {
  title:'A Healthier Family — Award Journey',
  image:'assets/video-carousel/C00004.JPG?v=20260825-3',
  video:'https://drive.usercontent.google.com/download?id=1aRhv3AofcfDAgF_IvFz-XChXpoe1Oqgh&export=download&confirm=t',
  source:'C00004.srt',
  caption:`For appointments:\n+91 89259 54625\n+91 72004 24271\n\nFrom a reported HbA1c of 8.8 to 5.8, his journey became a family-wide change. 🏆 By choosing better food, tracking blood sugar, reducing body weight, and staying connected with his health coach, healthier habits reached the whole home. ❤️\n\nWatch this inspiring journey and share it with a family ready to begin. 🙌\n\n#doctorfarmer #myhealthschool #diabetes #HbA1c #bloodsugarcontrol #diabetesmanagement #familyhealth #healthylifestyle #healthyhabits #nutrition #wellness #lifestylechanges`,
  videoCaptions:[`HbA1c 8.8 முதல் 5.8 வரை\nஉணவின் வெற்றி`,`உணவு பழக்கம் மாறியது\nகுடும்ப ஆரோக்கியம் மீண்டும் மலர்ந்தது`]
 },
 {
  title:'Gopalakrishnan — Three-Month Transformation',
  image:'assets/video-carousel/C00007.JPG?v=20260825-3',
  video:'https://drive.usercontent.google.com/download?id=1pU99i_6zm6Sv40RnmLr3BpthSLVj8TnE&export=download&confirm=t',
  source:'C00007.srt',
  caption:`For appointments:\n+91 89259 54625\n+91 72004 24271\n\nDiagnosed with an HbA1c around 13–13.5, Gopalakrishnan says committed food habits and steady guidance helped him achieve a major transformation within three months. 🏆 His progress then inspired him to support his sister and mother on their own diabetes journeys. ❤️\n\nWatch his story and share it with someone who needs the courage to start. 🙌\n\n#doctorfarmer #myhealthschool #diabetes #HbA1c #diabetesmanagement #bloodsugarcontrol #familyhealth #healthyhabits #discipline #healthjourney #motivation #lifestylechanges`,
  videoCaptions:[`HbA1c 13.5 இலிருந்து\nமூன்றே மாதங்களில் வந்த மாற்றம்`,`மூன்று மாத ஒழுக்கம்\nகுடும்பத்திற்கே புதிய நம்பிக்கை தந்தது`]
 },
 {
  title:'From Insulin to Hope — Award Journey',
  image:'assets/video-carousel/C00150.JPG?v=20260825-3',
  video:'https://drive.usercontent.google.com/download?id=1K7jWiG-OPCU2-8vNsIbmIiJxXyHKPyM9&export=download&confirm=t',
  source:'C00150.srt',
  caption:`For appointments:\n+91 89259 54625\n+91 72004 24271\n\nFacing diabetes before 30, insulin, medication, and depression felt overwhelming. Today, she celebrates an award, a renewed body and mind, and the confidence to become an “angel” who helps other families move forward. 🏆❤️\n\nWatch her powerful journey and share it with someone who needs hope today. 🙌\n\n#doctorfarmer #myhealthschool #diabetes #insulin #mentalwellness #diabetesjourney #healthtransformation #PositiveMindset #healthyhabits #familyhealth #motivation #lifestylechanges`,
  videoCaptions:[`Insulin சார்பிலிருந்து விடுதலை\nமனமும் உடலும் மீண்டும் மலர்ந்தது`,`Depression கடந்த மனம்\nஇன்று மீண்டும் நம்பிக்கையாக மலர்ந்தது`]
 },
 {
  title:'Food, Freedom and a New Life',
  image:'assets/video-carousel/P1012693.JPG?v=20260825-3',
  video:'https://drive.usercontent.google.com/download?id=1Rea26pzWFwXi_bIxK5q2YJZkJXQmD1fF&export=download&confirm=t',
  source:'P1012693.srt',
  caption:`For appointments:\n+91 89259 54625\n+91 72004 24271\n\nShe describes progress beyond diabetes—from BP concerns, sleep disorder, weight challenges, and other health struggles to better sleep, stronger food control, and a freer mind. 🏆 Her award now stands as a message to her husband, son, and everyone waiting to make a change. ❤️\n\nWatch her inspiring journey and share it with someone ready to choose health. 🙌\n\n#doctorfarmer #myhealthschool #diabetes #bloodpressure #sleephealth #weightmanagement #healthyfood #mindset #familyhealth #healthtransformation #wellness #lifestylechanges`,
  videoCaptions:[`BP, sleep disorder கடந்து\nஉணவே மருந்தான வெற்றி`,`உணவுக் கட்டுப்பாடு வளர்ந்தது\nவாழ்க்கையின் சுதந்திரம் மீண்டும் திரும்பியது`]
 }
];
let current=0,visible=[...posters.keys()],activeFilter='all',viewerMode='doctor';
const dayFmt=new Intl.DateTimeFormat('en-IN',{weekday:'short',day:'numeric',month:'short'}),rangeFmt=new Intl.DateTimeFormat('en-IN',{day:'numeric',month:'short',year:'numeric'});
const campaigns=Array.from({length:12},(_,i)=>{const d=new Date(2026,7+i,1),isAugust=i===0,isSeptember=i===1,isOctober=i===2,isNovember=i===3,isDecember=i===4;return{key:`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`,label:d.toLocaleDateString('en-IN',{month:'long',year:'numeric'}),ready:isAugust||isSeptember||isOctober||isNovember||isDecember,count:isAugust?6:isSeptember?30:isOctober?31:isNovember?30:isDecember?31:0,target:isAugust?6:(isOctober||isDecember)?31:30,cover:isAugust?'assets/august-26.png':isSeptember?'assets/01.png':isOctober?'assets/october-01.png':isNovember?'assets/november-01.png':isDecember?'assets/december-01.png':null,note:'Next monthly collection',startDate:isAugust?'2026-08-26':`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-01`,posts:isAugust?augustPosters:isSeptember?septemberPosters:isOctober?octoberPosters:isNovember?novemberPosters:isDecember?decemberPosters:null,captions:isAugust?augustCaptions:isSeptember?septemberCaptions:isOctober?octoberCaptions:isNovember?novemberCaptions:isDecember?decemberCaptions:null}});
function renderMonthCards(){const host=document.querySelector('#month-cards');host.innerHTML='';campaigns.forEach(c=>{const button=document.createElement('button');button.className=`month-card${c.key===startInput.value.slice(0,7)?' active':''}${c.ready?'':' pending'}`;button.disabled=!c.ready;button.innerHTML=c.ready?`<img src="${c.cover}" alt=""><span class="month-card-shade"></span><span class="month-card-copy"><small>READY · ${c.count}/${c.target} POSTS</small><strong>${c.label}</strong><em>Open collection →</em></span>`:`<span class="month-card-empty">+</span><span class="month-card-copy"><small>AWAITING POSTERS · ${c.count}/${c.target}</small><strong>${c.label}</strong><em>${c.note}</em></span>`;button.addEventListener('click',()=>{startInput.value=c.startDate;posters=c.posts;captions=c.captions;activeFilter='all';collectionContent.hidden=false;document.querySelectorAll('.filter').forEach(filter=>filter.classList.toggle('active',filter.dataset.filter==='all'));document.querySelector('#selected-month').textContent=c.label;renderMonthCards();render();document.querySelector('.schedule-bar').scrollIntoView({behavior:'smooth'})});host.append(button)})}
function dateFor(i){const d=new Date(`${startInput.value}T12:00:00`);d.setDate(d.getDate()+i);return d}
function render(filter=activeFilter){
 activeFilter=filter;visible=[];calendar.innerHTML='';const grid=document.createElement('div');grid.className='grid';
 posters.forEach((p,i)=>{if(filter!=='all'&&p.category!==filter)return;visible.push(i);const d=dateFor(i),card=document.createElement('article');card.className='card';card.innerHTML=`<button class="poster-button" data-index="${i}" aria-label="View ${p.title} poster scheduled for ${dayFmt.format(d)}"><span class="date-badge"><strong>${d.getDate()}</strong><span>${d.toLocaleDateString('en-IN',{weekday:'short'}).toUpperCase()}</span></span><img src="${p.src}" alt="Motivational health poster photographed at ${p.title}" loading="lazy"></button><button class="card-copy" type="button" data-index="${i}" aria-label="Copy caption and download ${p.title} poster"><span aria-hidden="true">⇩</span> Download + copy</button><div class="meta"><span class="num">${String(i+1).padStart(2,'0')}</span><div><h3>${p.title}</h3><p>${dayFmt.format(d)} · ${p.category==='heritage'?'Heritage':p.category==='hills'?'Hills & forest':'Water & coast'}</p></div></div>`;grid.append(card)});
 calendar.append(grid);
 document.querySelectorAll('.filter').forEach(button=>{const count=button.dataset.filter==='all'?posters.length:posters.filter(p=>p.category===button.dataset.filter).length;button.querySelector('span').textContent=count});document.querySelector('#empty').hidden=visible.length>0;document.querySelector('#schedule-range').textContent=`${rangeFmt.format(dateFor(0))} — ${rangeFmt.format(dateFor(posters.length-1))}`;document.querySelector('#schedule-note').textContent=`One Instagram post every day for ${posters.length} days`;
}
function setViewerBrand(mode){const doctor=mode==='doctor';viewerAvatar.src=viewerCaptionAvatar.src=doctor?'assets/profile.png':'assets/logos/fofitos.png';viewerAvatar.alt=doctor?'Doctor Farmer':'FOFITOS';viewerUsername.textContent=doctor?'@iamdoctorfarmer':'FOFITOS';viewerAppointment.hidden=!doctor;viewerCaptionAvatar.hidden=!doctor;viewer.classList.toggle('fofitos-view',!doctor);document.querySelector('.prev').hidden=false;document.querySelector('.next').hidden=false}
function showViewerFromTop(){viewer.scrollTop=0;viewer.scrollLeft=0;document.querySelector('.insta-caption').scrollTop=0;if(!viewer.open)viewer.showModal();requestAnimationFrame(()=>{viewer.scrollTop=0;viewer.scrollLeft=0;document.querySelector('.insta-caption').scrollTop=0})}
function captionEmojis(message){const text=message.toLowerCase();if(/morning|begin|start|new day/.test(text))return'🌅✨';if(/rest|recover|sleep|pause|energy/.test(text))return'😴🔋';if(/calm|quiet|still|peace|clarity|mindful/.test(text))return'🧘‍♂️🌿';if(/walk|move|step|climb|forward|journey|path/.test(text))return'🚶‍♂️🏔️';if(/food|meal|nourish|nutrition/.test(text))return'🥗🌱';if(/strength|strong|body|fitness|workout/.test(text))return'💪🔥';if(/courage|fear|uncertain|unknown/.test(text))return'🦁🔥';if(/balance|steady|pace|rhythm/.test(text))return'⚖️🌿';if(/heal|health|wellbeing|care/.test(text))return'❤️‍🩹✨';if(/grow|build|habit|foundation|future/.test(text))return'🌱🧱';if(/discipline|consistent|effort|commit/.test(text))return'🎯💪';return'✨💪'}
function doctorCaption(index=current){const message=captions[index].replace(/\n\n#[\s\S]*$/,'').trim();return `${captionEmojis(message)} ${message}\n\n${doctorHashtags}`}
function openViewer(i){viewerMode='doctor';setViewerBrand(viewerMode);current=i;const p=posters[i],d=dateFor(i);viewerImage.src=p.src;viewerImage.alt=`Motivational poster at ${p.title}`;viewerTitle.textContent=`Post ${String(i+1).padStart(2,'0')} of ${posters.length}`;viewerCount.textContent=`${posters.length}-day health series`;viewerCaption.textContent=doctorCaption(i);viewerLocation.textContent=p.title;viewerDate.textContent=dayFmt.format(d).toUpperCase();copyCaptionButton.classList.remove('copied');copyCaptionButton.lastChild.textContent=' Copy + download';showViewerFromTop()}
function openFofitosViewer(i=0){viewerMode='fofitos';setViewerBrand(viewerMode);current=i;const p=fofitosPosts[i],d=new Date(`${p.date}T12:00:00`);viewerImage.src=p.src;viewerImage.alt=`Fofitos ${p.title} nutrition poster`;viewerTitle.textContent=`Post ${String(i+1).padStart(2,'0')} of ${fofitosPosts.length}`;viewerCount.textContent='Fofitos daily food series';viewerCaption.textContent=fofitosCaptions[i];viewerLocation.textContent=p.title;viewerDate.textContent=dayFmt.format(d).toUpperCase();copyCaptionButton.classList.remove('copied');copyCaptionButton.lastChild.textContent=' Copy + download';showViewerFromTop()}
function move(dir){if(viewerMode==='fofitos'){current=(current+dir+fofitosPosts.length)%fofitosPosts.length;openFofitosViewer(current);return}const pos=visible.indexOf(current);current=visible[(pos+dir+visible.length)%visible.length];openViewer(current)}
function completeCaption(index=current){return viewerMode==='fofitos'?fofitosCaptions[index]:`For appointments:\n+91 89259 54625\n+91 72004 24271\n\n${doctorCaption(index)}`}
async function posterBlob(index=current){const source=viewerMode==='fofitos'?fofitosPosts[index].src:posters[index].src;try{const response=await fetch(source);if(response.ok)return await response.blob()}catch(error){}const image=new Image();image.src=source;await image.decode();const canvas=document.createElement('canvas');canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;canvas.getContext('2d').drawImage(image,0,0);return await new Promise((resolve,reject)=>{try{canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('Image conversion failed')),'image/png')}catch(error){reject(error)}})}
async function downloadPoster(index=current){const blob=await posterBlob(index),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=viewerMode==='fofitos'?`fofitos-post-${String(index+1).padStart(2,'0')}.png`:`doctor-farmer-post-${String(index+1).padStart(2,'0')}.png`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function setActionLabel(button,label){if(button===copyCaptionButton)button.lastChild.textContent=` ${label}`;else button.innerHTML=`<span aria-hidden="true">⇩</span> ${label}`}
async function copyCaption(index=current,button=copyCaptionButton){current=index;const text=completeCaption(index);setActionLabel(button,'Preparing…');button.disabled=true;let copied=false,downloaded=false;try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(text)}else{const area=document.createElement('textarea');area.value=text;area.setAttribute('readonly','');area.style.cssText='position:fixed;opacity:0;pointer-events:none';document.body.append(area);area.select();if(!document.execCommand('copy'))throw new Error('Copy failed');area.remove()}copied=true}catch(error){}try{await downloadPoster(index);downloaded=true}catch(error){}if(copied&&downloaded){button.classList.add('copied');setActionLabel(button,'Copied + downloaded!')}else if(copied){setActionLabel(button,'Copied · download blocked')}else if(downloaded){setActionLabel(button,'Downloaded · copy blocked')}else{setActionLabel(button,'Browser blocked both')}setTimeout(()=>{button.classList.remove('copied');button.disabled=false;setActionLabel(button,button===copyCaptionButton?'Copy + download':'Download + copy')},2600)}
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelector('.filter.active').classList.remove('active');b.classList.add('active');render(b.dataset.filter)}));
calendar.addEventListener('click',e=>{const copy=e.target.closest('.card-copy');if(copy){viewerMode='doctor';copyCaption(Number(copy.dataset.index),copy);return}const poster=e.target.closest('.poster-button');if(poster)openViewer(Number(poster.dataset.index))});document.querySelector('.close').onclick=()=>viewer.close();document.querySelector('.prev').onclick=()=>move(-1);document.querySelector('.next').onclick=()=>move(1);document.querySelector('.like').onclick=e=>{e.currentTarget.classList.toggle('liked');e.currentTarget.textContent=e.currentTarget.classList.contains('liked')?'♥':'♡'};copyCaptionButton.addEventListener('click',()=>copyCaption(current,copyCaptionButton));viewer.addEventListener('click',e=>{if(e.target===viewer)viewer.close()});document.addEventListener('keydown',e=>{if(!viewer.open)return;if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1)});
function fofitosMonthPosts(monthDate){return fofitosPosts.map((post,index)=>({post,index})).filter(({post})=>{const date=new Date(`${post.date}T12:00:00`);return date.getFullYear()===monthDate.getFullYear()&&date.getMonth()===monthDate.getMonth()})}
function renderEmptyMonths(isFofitos=false){emptyMonthGrid.innerHTML='';Array.from({length:12},(_,i)=>new Date(2026,7+i,1)).forEach(date=>{const entries=isFofitos?fofitosMonthPosts(date):[],ready=entries.length>0,month=document.createElement('button'),label=date.toLocaleDateString('en-IN',{month:'long',year:'numeric'});month.type='button';month.className=`month-card${ready?'':' pending'}`;month.disabled=!ready;month.innerHTML=ready?`<img src="${entries[0].post.src}" alt=""><span class="month-card-shade"></span><span class="month-card-copy"><small>READY · ${entries.length} POSTS</small><strong>${label}</strong><em>Open collection →</em></span>`:`<span class="month-card-empty">+</span><span class="month-card-copy"><small>AWAITING POSTERS · 0/30</small><strong>${label}</strong><em>Next monthly collection</em></span>`;if(ready)month.addEventListener('click',()=>{document.querySelectorAll('#empty-month-grid .month-card').forEach(card=>card.classList.remove('active'));month.classList.add('active');renderFofitosReady(entries);channelReady.hidden=false;channelReady.scrollIntoView({behavior:'smooth'})});emptyMonthGrid.append(month)})}
function renderFofitosReady(entries=fofitosMonthPosts(new Date(2026,7,1))){const firstDate=new Date(`${entries[0].post.date}T12:00:00`),lastDate=new Date(`${entries.at(-1).post.date}T12:00:00`),monthLabel=firstDate.toLocaleDateString('en-IN',{month:'long',year:'numeric'});document.querySelector('#channel-ready-title').textContent=monthLabel;document.querySelector('#channel-ready .schedule-bar p strong').textContent=`${rangeFmt.format(firstDate)} — ${rangeFmt.format(lastDate)}`;document.querySelector('#channel-ready .schedule-bar p span').textContent=`${entries.length} Instagram posts scheduled`;document.querySelector('#channel-ready .filter span').textContent=entries.length;channelReadyGrid.classList.add('schedule-view');channelReadyGrid.innerHTML=`<div class="grid fofitos-schedule">${entries.map(({post,index})=>{const d=new Date(`${post.date}T12:00:00`);return `<article class="card"><button class="poster-button" data-fofitos-view="${index}" aria-label="View ${post.title} poster scheduled for ${dayFmt.format(d)}"><span class="date-badge"><strong>${d.getDate()}</strong><span>${d.toLocaleDateString('en-IN',{weekday:'short'}).toUpperCase()}</span></span><img src="${post.src}" alt="Fofitos ${post.title} food poster" loading="lazy"></button><button class="card-copy" type="button" data-fofitos-copy="${index}" aria-label="Copy caption and download ${post.title} poster"><span aria-hidden="true">⇩</span> Download + copy</button><div class="meta"><span class="num">${String(index+1).padStart(2,'0')}</span><div><h3>${post.title}</h3><p>${dayFmt.format(d)} · Fofitos</p></div></div></article>`}).join('')}</div>`;channelReadyGrid.querySelectorAll('[data-fofitos-view]').forEach(button=>button.addEventListener('click',()=>openFofitosViewer(Number(button.dataset.fofitosView))));channelReadyGrid.querySelectorAll('[data-fofitos-copy]').forEach(button=>button.addEventListener('click',event=>{viewerMode='fofitos';copyCaption(Number(button.dataset.fofitosCopy),event.currentTarget)}))}
async function copyTextValue(text,button){let copied=false;try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(text);copied=true}}catch(error){}if(!copied){const area=document.createElement('textarea');area.value=text;area.setAttribute('readonly','');area.style.cssText='position:fixed;opacity:0;pointer-events:none';document.body.append(area);area.select();copied=document.execCommand('copy');area.remove()}if(!copied){button.textContent='Copy failed';return}button.classList.add('copied');const original=button.textContent;button.textContent='Copied!';setTimeout(()=>{button.classList.remove('copied');button.textContent=original},1800)}
async function downloadMediaAndCopyCaption(item,button){const original=button.textContent;button.disabled=true;button.textContent='Preparing downloads…';let imageStarted=false,videoStarted=false,copied=false;try{const imageLink=document.createElement('a');imageLink.href=item.image;imageLink.download=item.image.split('/').pop().split('?')[0];document.body.append(imageLink);imageLink.click();imageLink.remove();imageStarted=true}catch(error){}try{const videoLink=document.createElement('a');videoLink.href=item.video;videoLink.target='_blank';videoLink.rel='noopener';document.body.append(videoLink);videoLink.click();videoLink.remove();videoStarted=true}catch(error){}try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(item.caption);copied=true}}catch(error){}if(!copied){const area=document.createElement('textarea');area.value=item.caption;area.setAttribute('readonly','');area.style.cssText='position:fixed;opacity:0;pointer-events:none';document.body.append(area);area.select();copied=document.execCommand('copy');area.remove()}const complete=imageStarted&&videoStarted&&copied;button.classList.toggle('copied',complete);button.textContent=complete?'Image + video downloaded · caption copied!':copied?'Caption copied · check downloads':'Downloads started · copy blocked';setTimeout(()=>{button.classList.remove('copied');button.disabled=false;button.textContent=original},2800)}
function renderVideoCarousels(){videoCarouselGrid.innerHTML=doctorVideoCarousels.map((item,index)=>`<article class="video-carousel-entry"><figure class="video-carousel-cover"><img src="${item.image}" alt="${item.title} award ceremony cover"><figcaption><strong>${item.title}</strong><small>Source: ${item.source}</small></figcaption></figure><div class="video-caption-stack"><section class="caption-panel"><div class="caption-panel-head"><strong>Instagram caption</strong><button class="caption-copy caption-download-copy" type="button" data-caption-copy="${index}">Download image + video + copy caption</button></div><p class="caption-text">${item.caption}</p></section><section class="caption-panel"><div class="caption-panel-head"><strong>Video Captions</strong></div><div class="video-caption-options">${item.videoCaptions.map((caption,option)=>`<div class="video-caption-option"><div class="video-caption-option-head"><small>Option ${option+1}</small><button class="caption-copy" type="button" data-video-copy="${index}" data-video-option="${option}">Copy option ${option+1}</button></div><p class="caption-text video-short">${caption}</p></div>`).join('')}</div></section></div></article>`).join('');videoCarouselGrid.querySelectorAll('[data-caption-copy]').forEach(button=>button.addEventListener('click',()=>downloadMediaAndCopyCaption(doctorVideoCarousels[Number(button.dataset.captionCopy)],button)));videoCarouselGrid.querySelectorAll('[data-video-copy]').forEach(button=>button.addEventListener('click',()=>copyTextValue(doctorVideoCarousels[Number(button.dataset.videoCopy)].videoCaptions[Number(button.dataset.videoOption)],button)))}
function routeChannel(){
 const route=location.hash.slice(1)||'channels',match=route.match(/^(doctor-farmer|fofitos|longer-life)(?:-(posts|reels|carousels|video-carousel))?$/),brandKey=match?.[1],format=match?.[2],brandName=brandKey==='doctor-farmer'?'Doctor Farmer':brandKey==='fofitos'?'FOFITOS':'Longer Life Wellness';
 channelDashboard.hidden=route!=='channels';contentTypePage.hidden=!(brandKey&&!format);channelWorkspace.hidden=route!=='doctor-farmer-posts';emptyChannel.hidden=route!=='fofitos-posts'&&route!=='longer-life-posts';videoCarouselPage.hidden=route!=='doctor-farmer-video-carousel';formatEmptyPage.hidden=!(['reels','carousels'].includes(format)||(format==='video-carousel'&&brandKey!=='doctor-farmer'));
 if(brandKey&&!format){contentTypeTitle.textContent=brandName;document.querySelector('#content-type-posts').href=`#${brandKey}-posts`;document.querySelector('#content-type-reels').href=`#${brandKey}-reels`;document.querySelector('#content-type-carousels').href=`#${brandKey}-carousels`;document.querySelector('#content-type-video-carousel').href=`#${brandKey}-video-carousel`;requestAnimationFrame(()=>contentTypePage.scrollIntoView())}
 else if(route==='doctor-farmer-posts'){collectionContent.hidden=true;startInput.value='';document.querySelector('#selected-month').textContent='';renderMonthCards();requestAnimationFrame(()=>channelWorkspace.scrollIntoView())}
 else if(route==='fofitos-posts'||route==='longer-life-posts'){const isFofitos=route==='fofitos-posts';document.querySelector('#posts-back').href=isFofitos?'#fofitos':'#longer-life';emptyChannelTitle.innerHTML=isFofitos?'REAL FOOD.<br>REAL STORIES.':'LONGER LIFE';emptyChannelNote.textContent=isFofitos?`${fofitosPosts.length} edited Fofitos posters are scheduled from 25 August, each with its own caption and download action.`:'No posts have been added to this channel yet.';channelReady.hidden=true;if(isFofitos)renderFofitosReady();renderEmptyMonths(isFofitos);requestAnimationFrame(()=>emptyChannel.scrollIntoView())}
 else if(route==='doctor-farmer-video-carousel'){renderVideoCarousels();requestAnimationFrame(()=>videoCarouselPage.scrollIntoView())}
 else if(['reels','carousels','video-carousel'].includes(format)){formatBrand.textContent=brandName;formatEmptyTitle.textContent=format==='video-carousel'?'VIDEO CAROUSEL':format.toUpperCase();formatBack.href=`#${brandKey}`;requestAnimationFrame(()=>formatEmptyPage.scrollIntoView())}
 else if(route!=='channels')history.replaceState(null,'',location.pathname+location.search+'#channels')
}
window.addEventListener('hashchange',routeChannel);startInput.value='';document.querySelector('#selected-month').textContent='';renderMonthCards();routeChannel();
